---
version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '%(levelname)s %(asctime)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  local:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    filename: parsing/schools/{school}/logs/parsing.log
    formatter: simple
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  {module}:
    level: DEBUG
    handlers:
    - local
    propogate: true
...
