# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-04 04:29


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataupdate',
            old_name='last_updated',
            new_name='timestamp',
        ),
    ]
