# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_reaction_time_created'),
        ('analytics', '0004_remove_analyticscoursesearch_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticscoursesearch',
            name='courses',
        ),
        migrations.AddField(
            model_name='analyticscoursesearch',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
