# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20160605_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticscoursesearch',
            name='query',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
