# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_analyticscoursesearch_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticscoursesearch',
            name='is_advanced',
            field=models.BooleanField(default=False),
        ),
    ]
