# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-23 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_analyticscoursesearch_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticscoursesearch',
            name='sem_name',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticscoursesearch',
            name='year',
            field=models.CharField(default='temp', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticstimetable',
            name='sem_name',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticstimetable',
            name='year',
            field=models.CharField(default='temp', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedtimetable',
            name='sem_name',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedtimetable',
            name='year',
            field=models.CharField(default='temp', max_length=4),
            preserve_default=False,
        ),
    ]
