# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-24 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_auto_20170223_1316'),
        ('analytics', '0010_calendarexport'),
    ]

    operations = [
    ]
