# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-08 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_finalexammodalview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedTimetableView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('shared_timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.SharedTimetable')),
            ],
        ),
    ]
