# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-24 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticscoursesearch',
            name='_semester',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticstimetable',
            name='_semester',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedtimetable',
            name='_semester',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analyticscoursesearch',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Semester'),
        ),
        migrations.AlterField(
            model_name='analyticstimetable',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Semester'),
        ),
        migrations.AlterField(
            model_name='sharedtimetable',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Semester'),
        ),
    ]
