# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-24 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticscoursesearch',
            old_name='semester',
            new_name='_semester',
        ),
        migrations.RenameField(
            model_name='analyticstimetable',
            old_name='semester',
            new_name='_semester',
        ),
        migrations.RenameField(
            model_name='sharedtimetable',
            old_name='semester',
            new_name='_semester',
        ),
    ]
