# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-12 00:25
from __future__ import unicode_literals
from operator import attrgetter

from django.db import migrations

from update_semester_field import get_update_operation

tables_to_update = [
  'SharedTimetable',
  'AnalyticsTimetable',
  'AnalyticsCourseSearch',
]

class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_auto_20170311_1924'),
    ]

    operations = [
      migrations.RunPython(get_update_operation('analytics', 
                                                tables_to_update,
                                                attrgetter('school'))),
    ]
