# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-12 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_finalexammodalview'),
        ('analytics', '0013_update_semester_field'),
    ]

    operations = [
    ]
