# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-25 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_auto_20170224_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticscoursesearch',
            name='sem_name',
        ),
        migrations.RemoveField(
            model_name='analyticscoursesearch',
            name='year',
        ),
        migrations.RemoveField(
            model_name='analyticstimetable',
            name='sem_name',
        ),
        migrations.RemoveField(
            model_name='analyticstimetable',
            name='year',
        ),
        migrations.RemoveField(
            model_name='sharedtimetable',
            name='sem_name',
        ),
        migrations.RemoveField(
            model_name='sharedtimetable',
            name='year',
        ),
    ]
