# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-03 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_sharedtimetableview_student'),
        ('analytics', '0015_facebookalertclick_facebookalertview'),
    ]

    operations = [
    ]
