# Generated by Django 3.2.10 on 2021-12-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0019_auto_20210620_2150"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FinalExamModalView",
        ),
    ]
