# Generated by Django 3.2.20 on 2023-10-07 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("analytics", "0022_uierrorlog"),
        ("analytics", "0023_alter_uierrorlog_user"),
        ("analytics", "0024_alter_uierrorlog_options"),
    ]

    dependencies = [
        ("analytics", "0021_auto_20230203_1230"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("student", "0046_delete_registrationtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="UIErrorLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_occurred", models.DateTimeField(auto_now_add=True)),
                ("message", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=100)),
                ("stack", models.TextField()),
                ("componentStack", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-time_occurred"],
                "abstract": False,
            },
        ),
    ]
