# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-20 02:14
from __future__ import unicode_literals

from django.db import migrations

def load_tos(apps, schema_editor):
    Tos = apps.get_model('timetable', 'TermOfService')
    tos = Tos(id=1)
    tos.save()

class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_tos),
    ]
