# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-20 02:31
from __future__ import unicode_literals

from django.db import migrations

def load_agreement(apps, schema_editor):
    agreement_model = apps.get_model('agreement', 'Agreement')
    agreement = agreement_model(id=1)
    agreement.save()

class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_agreement),
    ]
