# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-21 00:27
from __future__ import unicode_literals

from datetime import datetime

from django.db import migrations

def load_agreement(apps, schema_editor):
    agreement_model = apps.get_model('agreement', 'Agreement')
    agreement_model.objects.create(last_updated=datetime.now())

class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_agreement),
    ]
