# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-22 18:04
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0003_auto_20170615_1828'),
        ('agreement', '0003_auto_20170707_0757'),
    ]

    operations = [
    ]
