# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-24 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0006_add_hopkinsIT_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
