# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-10 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0036_auto_20210410_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhed', models.CharField(default=b'', max_length=255, null=True)),
                ('email_address', models.CharField(default=b'', max_length=255, null=True)),
                ('students', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
