# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='first_name',
            field=models.CharField(default=b'', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='last_name',
            field=models.CharField(default=b'', max_length=255, null=True),
        ),
    ]
