# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-21 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0034_merge'),
        ('timetable', '0033_section_course_section_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisors', models.ManyToManyField(related_name='advisors', to='student.Student')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='student.Student')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='transcript_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Transcript'),
        ),
    ]
