# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-01 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_auto_20210323_2126'),
        ('timetable', '0033_section_course_section_id'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together=set([('owner', 'semester')]),
        ),
    ]
