# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-26 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='transcript_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.Transcript'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='advisors',
            field=models.ManyToManyField(related_name='student_forum_transcript', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_forum_transcript', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_forum_transcript', to='timetable.Semester'),
        ),
    ]
