# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-27 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_comment_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='transcript_id',
            new_name='transcript',
        ),
        migrations.RenameField(
            model_name='transcript',
            old_name='semester_id',
            new_name='semester',
        ),
    ]
