# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-28 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210327_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='transcript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Transcript'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='advisors',
            field=models.ManyToManyField(related_name='student_transcripts', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_transcripts', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Semester'),
        ),
    ]
