# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0033_section_course_section_id'),
        ('student', '0034_merge'),
        ('forum', '0007_auto_20210328_0053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together=set([('owner', 'semester')]),
        ),
    ]
