# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0018_update_semester_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalExamShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('exam_json', jsonfield.fields.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
