# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-03 20:51
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalexamshare',
            name='exam_json',
            field=jsonfield.fields.JSONField(),
        ),
    ]
