

url = 'https://cs90prod.chapman.edu/psc/CS90PROD_1/EMPLOYEE/SA/c/COMMUNITY_ACCESS.CLASS_SEARCH.GBL'

'PORTALPARAM_PTCNAV' : 'XC_GUEST_CLASS_SCHEDULE',
'EOPP.SCNode' : 'EMPL',
'EOPP.SCPortal' : 'EMPLOYEE',
'EOPP.SCName' : 'ADMN_SEARCH_FOR_CLASSES__GUES',
'EOPP.SCLabel' : '',
'EOPP.SCPTcname' : 'PT_PTPP_SCFNAV_BASEPAGE_SCR',
'FolderPath' : 'PORTAL_ROOT_OBJECT.PORTAL_BASE_DATA.CO_NAVIGATION_COLLECTIONS.ADMN_SEARCH_FOR_CLASSES__GUES.ADMN_S201505070932101643447597',
'IsFolder' : 'false'
