/*
Copyright (C) 2017 Semester.ly Technologies, LLC

Semester.ly is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Semester.ly is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
*/

// CALENDAR
export const EXPORT_SIS_TIMETABLE = "EXPORT_SIS_TIMETABLE";

// CLASSMATES
export const REQUEST_MOST_CLASSMATES = "REQUEST_MOST_CLASSMATES";

// EXPLORATON & SEARCH
export const RECEIVE_SEARCH_RESULTS = "RECEIVE_SEARCH_RESULTS";
export const PAGINATE_ADVANCED_SEARCH_RESULTS = "PAGINATE_ADVANCED_SEARCH_RESULTS";
export const CLEAR_ADVANCED_SEARCH_PAGINATION = "CLEAR_ADVANCED_SEARCH_PAGINATION";

// FRIENDS
export const FRIENDS_RECEIVED = "FRIENDS_RECEIVED";
export const REQUEST_FRIENDS = "REQUEST_FRIENDS";

// INIT
export const INIT_STATE = "INIT_STATE";

// INTEGRATIONS
export const TOGGLE_INTEGRATION_MODAL = "TOGGLE_INTEGRATION_MODAL";
export const OPEN_INTEGRATION_MODAL = "OPEN_INTEGRATION_MODAL";

// NOTIFICATIONS
export const TOKEN_REGISTERED = "TOKEN_REGISTERED";
export const UNREGISTER_TOKEN = "UNREGISTER_TOKEN";

// OPTIONAL COURSES
export const ADD_REMOVE_OPTIONAL_COURSE = "ADD_REMOVE_OPTIONAL_COURSE";
export const REMOVE_OPTIONAL_COURSE_BY_ID = "REMOVE_OPTIONAL_COURSE_BY_ID";
export const CLEAR_OPTIONAL_COURSES = "CLEAR_OPTIONAL_COURSES";

// FIND FRIENDS & PEER MODAL
export const TOGGLE_PEER_MODAL = "TOGGLE_PEER_MODAL";
export const PEER_MODAL_LOADING = "PEER_MODAL_LOADING";
export const PEER_MODAL_LOADED = "PEER_MODAL_LOADED";

// PREFERENCE MODAL
export const TOGGLE_PREFERENCE_MODAL = "TOGGLE_PREFERENCE_MODAL";

// TIMETABLE PREFERENCES
export const TOGGLE_CONFLICTS = "TOGGLE_CONFLICTS";
export const TURN_CONFLICTS_ON = "TURN_CONFLICTS_ON";
export const SET_ALL_PREFERENCES = "SET_ALL_PREFERENCES";
export const ADD_METRIC = "ADD_METRIC";
export const REMOVE_METRIC = "REMOVE_METRIC";
export const SWITCH_METRIC = "SWITCH_METRIC";
export const TOGGLE_METRIC_ORDER = "TOGGLE_METRIC_ORDER";
