# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='meeting_section',
        ),
        migrations.AddField(
            model_name='section',
            name='textbooks',
            field=models.ManyToManyField(through='timetable.TextbookLink', to='timetable.Textbook'),
        ),
    ]
