# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20160520_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='info',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='course',
            name='notes',
            field=models.TextField(default=b''),
        ),
    ]
