# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20160926_1822'),
        ('timetable', '0005_auto_20161026_1511'),
    ]

    operations = [
    ]
