# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-27 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20161023_1916'),
        ('timetable', '0005_auto_20161026_1511'),
    ]

    operations = [
    ]
