# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-01 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20161026_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='areas',
            field=models.CharField(default=b'', max_length=600, null=True),
        ),
    ]
