# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-20 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20161020_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
