# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-20 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20161020_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(default=b'', null=True),
        ),
    ]
