# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-02 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20161101_1541'),
        ('timetable', '0006_auto_20161031_2057'),
    ]

    operations = [
    ]
