# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-21 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sem_name',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='year',
            field=models.CharField(default='temp', max_length=4),
            preserve_default=False,
        ),
    ]
