# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-18 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='was_full',
            field=models.BooleanField(default=False),
        ),
    ]
