# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_course_corequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='geneds',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
