# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-24 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_auto_20170224_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.Semester'),
            preserve_default=False,
        ),
    ]
