# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-25 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_section_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='sem_name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='year',
        ),
    ]
