# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-12 00:25
from __future__ import unicode_literals
from operator import attrgetter

from django.db import migrations

from update_semester_field import get_update_operation

tables_to_update = [
  'Section',
]


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_section_semester'),
    ]

    operations = [
      migrations.RunPython(get_update_operation('timetable', 
                                                tables_to_update,
                                                attrgetter('course.school'))),      
    ]
