# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-12 00:38
"""
This migration takes every Y section and replaces it with one F section and one
S section
"""

from __future__ import unicode_literals

from django.db import migrations


def move_y_courses(apps, schema_editor):
  """ Add values to table.sem_name and table.year based on table.semester """
  Semester = apps.get_model('timetable', 'Semester')
  Section = apps.get_model('timetable', 'Section')

  fall_sem = Semester.objects.get(name='Fall', year='2016')
  winter_sem = Semester.objects.get(name='Winter', year='2017')
  num_y_courses = Section.objects.filter(_semester='Y').count()
  for section in Section.objects.filter(_semester='Y'):
    # change the Y section into F
    section.semester = fall_sem
    section.save()

    # create new S section by copying section and its offerings
    offerings = section.offering_set.all()
    section.semester = winter_sem
    section.pk = None
    section.save()
    for offering in offerings:
      offering.section = section
      offering.pk = None
      offering.save()


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_update_semester_field'),
    ]

    operations = [
      migrations.RunPython(move_y_courses)
    ]
