# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-09 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_migrate_uoft_y_courses'),
        ('timetable', '0009_section_was_full'),
    ]

    operations = [
    ]
