# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-04 22:26


from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='vector',
            field=picklefield.fields.PickledObjectField(default=None, editable=False, null=True),
        ),
    ]
