# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-15 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_termofservice'),
        ('timetable', '0015_merge'),
    ]

    operations = [
    ]
