# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-19 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='same_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.Course'),
        ),
    ]
