# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-14 20:50
from __future__ import unicode_literals

from django.db import migrations, models

def load_tos(apps, schema_editor):
    Tos = apps.get_model('timetable', 'TermOfService')
    tos = Tos(id=1)
    tos.save()

class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_merge'),
    ]

    operations = [
        migrations.RunPython(load_tos),
    ]
