# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-07 12:56


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_course_vector'),
        ('timetable', '0017_auto_20170518_2230'),
    ]

    operations = [
    ]
