# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-28 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_remove_section__semester'),
        ('timetable', '0016_course_vector'),
    ]

    operations = [
    ]
