# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-22 18:04


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_remove_section__semester'),
        ('timetable', '0018_merge'),
    ]

    operations = [
    ]
