# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-28 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_merge'),
        ('timetable', '0018_merge'),
    ]

    operations = [
    ]
