# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_merge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Updates',
        ),
    ]
