# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-10-07 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_auto_20170821_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDenIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course')),
                ('denIntegration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Integration')),
            ],
        ),
        migrations.CreateModel(
            name='DenIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
