# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-09 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_add_learning_den'),
        ('timetable', '0023_coursedenintegration_denintegration'),
    ]

    operations = [
    ]
