# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-26 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_auto_20170917_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='vector',
        ),
    ]
