# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_auto_20160410_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='areas',
            field=models.CharField(default=b'', max_length=300),
        ),
        migrations.AddField(
            model_name='ottawacourse',
            name='areas',
            field=models.CharField(default=b'', max_length=300),
        ),
        migrations.AddField(
            model_name='rutgerscourse',
            name='areas',
            field=models.CharField(default=b'', max_length=300),
        ),
        migrations.AddField(
            model_name='umdcourse',
            name='areas',
            field=models.CharField(default=b'', max_length=300),
        ),
    ]
