# Generated by Django 2.2.18 on 2021-02-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_add_learning_den'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='areas',
            field=models.CharField(default='', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='campus',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='corequisites',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='exclusions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='notes',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='unstopped_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='offering',
            name='location',
            field=models.CharField(default='TBA', max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='instructors',
            field=models.CharField(default='TBA', max_length=500),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(default='L', max_length=50),
        ),
    ]
