# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-04 22:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0023_add_learning_den"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="pos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(default=b"", null=True),
                default=list,
                size=None,
            ),
        ),
    ]
