# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-06 15:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0025_remove_course_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=b'', null=True), default=list, size=None),
        ),
    ]
