# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-19 15:53

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0026_course_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="writing_intensive",
            field=models.TextField(default=b"", null=True),
        ),
    ]
