# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.2 on 2019-02-19 15:53
=======
# Generated by Django 1.9.2 on 2019-02-06 17:07
>>>>>>> 96cb02b0f4af0cfaa0eafd59414ff0f2ba96edf6
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_course_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='writing_intensive',
            field=models.TextField(default=b'', null=True),
        ),
    ]
