# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_auto_20160411_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='num_credits',
        ),
        migrations.RemoveField(
            model_name='hopkinscourse',
            name='department',
        ),
        migrations.RemoveField(
            model_name='ottawacourse',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='ottawacourse',
            name='department',
        ),
        migrations.RemoveField(
            model_name='ottawacourse',
            name='num_credits',
        ),
        migrations.RemoveField(
            model_name='rutgerscourse',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='rutgerscourse',
            name='department',
        ),
        migrations.RemoveField(
            model_name='umdcourse',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='umdcourse',
            name='department',
        ),
        migrations.AlterField(
            model_name='hopkinscourse',
            name='areas',
            field=models.CharField(default=b'', max_length=300),
        ),
        migrations.AlterField(
            model_name='hopkinscourse',
            name='num_credits',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='umdcourse',
            name='num_credits',
            field=models.IntegerField(default=-1),
        ),
    ]
