# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0027_auto_20160423_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCourse',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(default=b'', max_length=1500)),
                ('unstopped_description', models.TextField(default=b'', max_length=1500)),
                ('campus', models.TextField(default=b'', max_length=300)),
                ('prerequisites', models.TextField(default=b'', max_length=1000)),
                ('exclusions', models.TextField(default=b'', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BaseCourseOffering',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('semester', models.CharField(max_length=2)),
                ('meeting_section', models.CharField(max_length=50)),
                ('instructors', models.CharField(default=b'TBA', max_length=500)),
                ('day', models.CharField(max_length=1)),
                ('time_start', models.CharField(max_length=15)),
                ('time_end', models.CharField(max_length=15)),
                ('location', models.CharField(default=b'TBA', max_length=200)),
                ('size', models.IntegerField(default=-1)),
                ('enrolment', models.IntegerField(default=-1)),
                ('waitlist', models.IntegerField(default=0)),
                ('section_type', models.CharField(default=b'L', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='unstopped_description',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='day',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='enrolment',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='id',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='location',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='meeting_section',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='section_type',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='size',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='time_start',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='waitlist',
        ),
        migrations.RemoveField(
            model_name='hopkinscourse',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='hopkinscourse',
            name='code',
        ),
        migrations.RemoveField(
            model_name='hopkinscourse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hopkinscourse',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='hopkinscourse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hopkinscourse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hopkinscourse',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='hopkinscourse',
            name='unstopped_description',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='day',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='enrolment',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='location',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='meeting_section',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='section_type',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='size',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='time_start',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='waitlist',
        ),
        migrations.RemoveField(
            model_name='ottawacourse',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='ottawacourse',
            name='code',
        ),
        migrations.RemoveField(
            model_name='ottawacourse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ottawacourse',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='ottawacourse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ottawacourse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ottawacourse',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='ottawacourse',
            name='unstopped_description',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='day',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='enrolment',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='meeting_section',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='section_type',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='size',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='time_start',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='waitlist',
        ),
        migrations.RemoveField(
            model_name='rutgerscourse',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='rutgerscourse',
            name='code',
        ),
        migrations.RemoveField(
            model_name='rutgerscourse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rutgerscourse',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='rutgerscourse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rutgerscourse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rutgerscourse',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='rutgerscourse',
            name='unstopped_description',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='day',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='enrolment',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='location',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='meeting_section',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='section_type',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='size',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='time_start',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='waitlist',
        ),
        migrations.RemoveField(
            model_name='umdcourse',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='umdcourse',
            name='code',
        ),
        migrations.RemoveField(
            model_name='umdcourse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='umdcourse',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='umdcourse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='umdcourse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='umdcourse',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='umdcourse',
            name='unstopped_description',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='day',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='enrolment',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='id',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='location',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='meeting_section',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='section_type',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='size',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='time_start',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='waitlist',
        ),
        migrations.AddField(
            model_name='course',
            name='basecourse_ptr',
            field=models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, default=1, serialize=False, to='timetable.BaseCourse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='basecourseoffering_ptr',
            field=models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, default=1, serialize=False, to='timetable.BaseCourseOffering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hopkinscourse',
            name='basecourse_ptr',
            field=models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, default=1, serialize=False, to='timetable.BaseCourse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hopkinscourseoffering',
            name='basecourseoffering_ptr',
            field=models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, default=1, serialize=False, to='timetable.BaseCourseOffering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ottawacourse',
            name='basecourse_ptr',
            field=models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, default=1, serialize=False, to='timetable.BaseCourse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ottawacourseoffering',
            name='basecourseoffering_ptr',
            field=models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, default=1, serialize=False, to='timetable.BaseCourseOffering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutgerscourse',
            name='basecourse_ptr',
            field=models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, default=1, serialize=False, to='timetable.BaseCourse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutgerscourseoffering',
            name='basecourseoffering_ptr',
            field=models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, default=1, serialize=False, to='timetable.BaseCourseOffering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='umdcourse',
            name='basecourse_ptr',
            field=models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, default=1, serialize=False, to='timetable.BaseCourse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='umdcourseoffering',
            name='basecourseoffering_ptr',
            field=models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, default=1, serialize=False, to='timetable.BaseCourseOffering'),
            preserve_default=False,
        ),
    ]
