# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-19 18:40

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0027_course_writing_intensive"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="sub_school",
            field=models.TextField(default=b"", null=True),
        ),
    ]
