# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0028_auto_20160508_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueensCourse',
            fields=[
                ('basecourse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timetable.BaseCourse')),
                ('cores', models.CharField(default=b'', max_length=200)),
                ('num_credits', models.FloatField(default=-1)),
                ('related_courses', models.ManyToManyField(blank=True, related_name='_queenscourse_related_courses_+', to='timetable.QueensCourse')),
            ],
            bases=('timetable.basecourse',),
        ),
        migrations.CreateModel(
            name='QueensCourseOffering',
            fields=[
                ('basecourseoffering_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timetable.BaseCourseOffering')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.QueensCourse')),
            ],
            bases=('timetable.basecourseoffering',),
        ),
        migrations.CreateModel(
            name='QueensLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('courseoffering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.QueensCourseOffering')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Textbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='queenscourseoffering',
            name='textbooks',
            field=models.ManyToManyField(through='timetable.QueensLink', to='timetable.Textbook'),
        ),
    ]
