# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-07 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0028_course_sub_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='writing_intensive',
        ),
    ]
