# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0029_auto_20160511_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queenscourse',
            name='cores',
        ),
    ]
