# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0029_remove_course_writing_intensive'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='writing_intensive',
            field=models.TextField(default=b'', null=True),
        ),
    ]
