# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0030_remove_queenscourse_cores'),
    ]

    operations = [
        migrations.AddField(
            model_name='queenscourseoffering',
            name='class_size',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='queenscourseoffering',
            name='num_enrolled',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='queenscourseoffering',
            name='num_waitlist',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='queenscourseoffering',
            name='waitlist_size',
            field=models.IntegerField(default=-1),
        ),
    ]
