# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-06-10 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0030_add_pilot_s19'),
    ]

    operations = [
        migrations.CreateModel(
            name='PILOTCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=250)),
                ('professor', models.CharField(max_length=250)),
                ('prerequisites', models.TextField(default=b'', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course')),
                ('same_as', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.PILOTCourse')),
            ],
        ),
        migrations.CreateModel(
            name='PILOTOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=1)),
                ('time_start', models.CharField(max_length=15)),
                ('time_end', models.CharField(max_length=15)),
                ('location', models.CharField(default=b'TBA', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PILOTSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=-1)),
                ('enrolment', models.IntegerField(default=-1)),
                ('waitlist', models.IntegerField(default=-1)),
                ('waitlist_size', models.IntegerField(default=-1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.PILOTCourse')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='pilotoffering',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.PILOTSection'),
        ),
    ]
