# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-11-05 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0031_add_date_start_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='is_short_course',
            field=models.BooleanField(default=False),
        ),
    ]
