# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0031_auto_20160511_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queenscourseoffering',
            name='class_size',
        ),
        migrations.RemoveField(
            model_name='queenscourseoffering',
            name='num_enrolled',
        ),
        migrations.RemoveField(
            model_name='queenscourseoffering',
            name='num_waitlist',
        ),
    ]
