# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-11-18 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0032_offering_is_short_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='course_section_id',
            field=models.IntegerField(default=0),
        ),
    ]
