# Generated by Django 2.2.18 on 2021-06-21 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_auto_20170910_2155'),
        ('timetable', '0033_section_course_section_id'),
    ]

    operations = [
    ]
