# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0033_auto_20160513_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[(b'\\uD83D\\uDD25', b'FIRE'), (b'\\uD83D\\uDE0D', b'LOVE'), (b'\\uD83D\\uDCA9', b'CRAP'), (b'\\uD83D\\uDE10', b'OKAY'), (b'\\uD83D\\uDE34', b'BORING'), (b'\\uD83D\\uDE29', b'HARD'), (b'\\uD83D\\uDE22', b'TEARS'), (b'\\uD83E\\uDD13', b'INTERESTING')], max_length=50)),
                ('course', models.ManyToManyField(to='timetable.BaseCourse')),
            ],
        ),
    ]
