# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_personaltimetable_last_updated'),
        ('timetable', '0035_auto_20160513_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
            preserve_default=False,
        ),
    ]
