# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0036_reaction_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueensCourseEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=5.0)),
                ('summary', models.TextField(max_length=1500)),
                ('professor', models.CharField(max_length=250)),
                ('course_code', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.QueensCourse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
