# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0037_queenscourseevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='breadths',
        ),
        migrations.AddField(
            model_name='basecourse',
            name='level',
            field=models.CharField(default=b'', max_length=30, null=True),
        ),
    ]
