# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20160517_1652'),
        ('timetable', '0038_auto_20160516_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=5.0)),
                ('summary', models.TextField(max_length=1500)),
                ('professor', models.CharField(max_length=250)),
                ('course_code', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=1)),
                ('start_time', models.CharField(max_length=15)),
                ('end_time', models.CharField(max_length=15)),
                ('location', models.CharField(default=b'TBA', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField(default=-1)),
                ('enrolment', models.IntegerField(default=-1)),
                ('waitlist', models.IntegerField(default=0)),
                ('section_type', models.CharField(default=b'L', max_length=50)),
                ('instructors', models.CharField(default=b'TBA', max_length=500)),
                ('semester', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TextbookLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Section')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Textbook')),
            ],
        ),
        migrations.RemoveField(
            model_name='basecourse',
            name='related_courses',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='basecourseoffering_ptr',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='textbooks',
        ),
        migrations.RemoveField(
            model_name='hopkinscourse',
            name='basecourse_ptr',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseevaluation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='basecourseoffering_ptr',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='course',
        ),
        migrations.RemoveField(
            model_name='hopkinscourseoffering',
            name='textbooks',
        ),
        migrations.RemoveField(
            model_name='hopkinslink',
            name='courseoffering',
        ),
        migrations.RemoveField(
            model_name='hopkinslink',
            name='textbook',
        ),
        migrations.RemoveField(
            model_name='link',
            name='courseoffering',
        ),
        migrations.RemoveField(
            model_name='link',
            name='textbook',
        ),
        migrations.RemoveField(
            model_name='ottawacourse',
            name='basecourse_ptr',
        ),
        migrations.RemoveField(
            model_name='ottawacourseevaluation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='basecourseoffering_ptr',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='course',
        ),
        migrations.RemoveField(
            model_name='ottawacourseoffering',
            name='textbooks',
        ),
        migrations.RemoveField(
            model_name='ottawalink',
            name='courseoffering',
        ),
        migrations.RemoveField(
            model_name='ottawalink',
            name='textbook',
        ),
        migrations.RemoveField(
            model_name='queenscourse',
            name='basecourse_ptr',
        ),
        migrations.RemoveField(
            model_name='queenscourseevaluation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='queenscourseoffering',
            name='basecourseoffering_ptr',
        ),
        migrations.RemoveField(
            model_name='queenscourseoffering',
            name='course',
        ),
        migrations.RemoveField(
            model_name='queenscourseoffering',
            name='textbooks',
        ),
        migrations.RemoveField(
            model_name='queenslink',
            name='courseoffering',
        ),
        migrations.RemoveField(
            model_name='queenslink',
            name='textbook',
        ),
        migrations.RemoveField(
            model_name='rutgerscourse',
            name='basecourse_ptr',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseevaluation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='basecourseoffering_ptr',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='course',
        ),
        migrations.RemoveField(
            model_name='rutgerscourseoffering',
            name='textbooks',
        ),
        migrations.RemoveField(
            model_name='rutgerslink',
            name='courseoffering',
        ),
        migrations.RemoveField(
            model_name='rutgerslink',
            name='textbook',
        ),
        migrations.RemoveField(
            model_name='umdcourse',
            name='basecourse_ptr',
        ),
        migrations.RemoveField(
            model_name='umdcourseevaluation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='basecourseoffering_ptr',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='course',
        ),
        migrations.RemoveField(
            model_name='umdcourseoffering',
            name='textbooks',
        ),
        migrations.RemoveField(
            model_name='umdlink',
            name='courseoffering',
        ),
        migrations.RemoveField(
            model_name='umdlink',
            name='textbook',
        ),
        migrations.RemoveField(
            model_name='course',
            name='basecourse_ptr',
        ),
        migrations.AddField(
            model_name='course',
            name='areas',
            field=models.CharField(default=b'', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='campus',
            field=models.TextField(default=b'', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='cores',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default=b'', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=b'', max_length=1500),
        ),
        migrations.AddField(
            model_name='course',
            name='exclusions',
            field=models.TextField(default=b'', max_length=1000),
        ),
        migrations.AddField(
            model_name='course',
            name='geneds',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default=b'', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='num_credits',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(default=b'', max_length=1000),
        ),
        migrations.AddField(
            model_name='course',
            name='related_courses',
            field=models.ManyToManyField(blank=True, related_name='_course_related_courses_+', to='timetable.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='unstopped_description',
            field=models.TextField(default=b'', max_length=1500),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='course',
            field=models.ManyToManyField(to='timetable.Course'),
        ),
        migrations.DeleteModel(
            name='BaseCourse',
        ),
        migrations.DeleteModel(
            name='BaseCourseOffering',
        ),
        migrations.DeleteModel(
            name='CourseOffering',
        ),
        migrations.DeleteModel(
            name='HopkinsCourse',
        ),
        migrations.DeleteModel(
            name='HopkinsCourseEvaluation',
        ),
        migrations.DeleteModel(
            name='HopkinsCourseOffering',
        ),
        migrations.DeleteModel(
            name='HopkinsLink',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='OttawaCourse',
        ),
        migrations.DeleteModel(
            name='OttawaCourseEvaluation',
        ),
        migrations.DeleteModel(
            name='OttawaCourseOffering',
        ),
        migrations.DeleteModel(
            name='OttawaLink',
        ),
        migrations.DeleteModel(
            name='QueensCourse',
        ),
        migrations.DeleteModel(
            name='QueensCourseEvaluation',
        ),
        migrations.DeleteModel(
            name='QueensCourseOffering',
        ),
        migrations.DeleteModel(
            name='QueensLink',
        ),
        migrations.DeleteModel(
            name='RutgersCourse',
        ),
        migrations.DeleteModel(
            name='RutgersCourseEvaluation',
        ),
        migrations.DeleteModel(
            name='RutgersCourseOffering',
        ),
        migrations.DeleteModel(
            name='RutgersLink',
        ),
        migrations.DeleteModel(
            name='UmdCourse',
        ),
        migrations.DeleteModel(
            name='UmdCourseEvaluation',
        ),
        migrations.DeleteModel(
            name='UmdCourseOffering',
        ),
        migrations.DeleteModel(
            name='UmdLink',
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course'),
        ),
        migrations.AddField(
            model_name='offering',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Section'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course'),
        ),
    ]
