# Generated by Django 3.2.17 on 2023-03-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0038_auto_20220130_1708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
