# Generated by Django 3.2.17 on 2023-03-03 21:51

from django.db import migrations
from django.db.models import Q


def delete_non_jhu_courses(apps, schema_editor):
    Course = apps.get_model("timetable", "Course")
    Course.objects.filter(~Q(school="jhu")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0039_auto_20230303_1640"),
    ]

    operations = [migrations.RunPython(delete_non_jhu_courses)]
