# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0040_auto_20160517_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
