# Generated by Django 3.2.17 on 2023-03-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0040_auto_20230303_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="school",
            field=models.CharField(max_length=100),
        ),
    ]
