# Generated by Django 3.2.17 on 2023-03-18 18:04

from django.db import migrations
from django.db.models import Q


def delete_old_semesters(apps, schema_editor):
    Semester = apps.get_model("timetable", "Semester")
    Semester.objects.filter(
        Q(year="2021")
        | Q(year="2020")
        | Q(year="2019")
        | Q(year="2018")
        | Q(year="2017")
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0041_alter_course_school"),
    ]

    operations = [migrations.RunPython(delete_old_semesters)]
