# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltimetable',
            name='has_conflict',
            field=models.BooleanField(default=False),
        ),
    ]
