# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_fbook_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='fbook_uid',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
