# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20160413_1752'),
        ('student', '0003_auto_20160420_1323'),
    ]

    operations = [
    ]
