# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0027_auto_20160423_1457'),
        ('student', '0004_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopkinsPersonalTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=2)),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
                ('course_offerings', models.ManyToManyField(to='timetable.HopkinsCourseOffering')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RutgersPersonalTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=2)),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
                ('course_offerings', models.ManyToManyField(to='timetable.RutgersCourseOffering')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UmdPersonalTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=2)),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
                ('course_offerings', models.ManyToManyField(to='timetable.UmdCourseOffering')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UofTPersonalTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=2)),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
                ('course_offerings', models.ManyToManyField(to='timetable.CourseOffering')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
