"""
Copyright (C) 2017 Semester.ly Technologies, LLC

Semester.ly is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Semester.ly is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 14:44


import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_reaction_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 9, 9, 44, 11, 335707)),
            preserve_default=False,
        ),
    ]
