# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_reaction_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 9, 9, 44, 11, 335707)),
            preserve_default=False,
        ),
    ]
