# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20160815_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='social_all',
            field=models.NullBooleanField(),
        ),
    ]
