# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20160926_1822'),
        ('student', '0009_student_emails_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='users',
            field=models.ManyToManyField(blank=True, to='timetable.Integration'),
        ),
    ]
