# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-03 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_emails_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedistrationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default=b'')),
            ],
        ),
    ]
