# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_personaltimetable_name'),
        ('student', '0010_auto_20160508_2308'),
    ]

    operations = [
    ]
