# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='users',
            new_name='integrations',
        ),
    ]
