# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-23 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20161005_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
