# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-23 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtoken',
            name='auth',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='endpoint',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='p256dh',
            field=models.TextField(default=b''),
        ),
    ]
