# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-23 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20161022_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationtoken',
            name='token',
        ),
    ]
