# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20161002_1701'),
        ('student', '0014_remove_registrationtoken_token'),
    ]

    operations = [
    ]
