# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_remove_registrationtoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=2)),
                ('time_start', models.CharField(max_length=15)),
                ('time_end', models.CharField(max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
