# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0038_auto_20160516_1510'),
        ('student', '0014_personaltimetable_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopkinspersonaltimetable',
            name='course_offerings',
        ),
        migrations.RemoveField(
            model_name='hopkinspersonaltimetable',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='hopkinspersonaltimetable',
            name='personaltimetable_ptr',
        ),
        migrations.RemoveField(
            model_name='rutgerspersonaltimetable',
            name='course_offerings',
        ),
        migrations.RemoveField(
            model_name='rutgerspersonaltimetable',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='rutgerspersonaltimetable',
            name='personaltimetable_ptr',
        ),
        migrations.RemoveField(
            model_name='umdpersonaltimetable',
            name='course_offerings',
        ),
        migrations.RemoveField(
            model_name='umdpersonaltimetable',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='umdpersonaltimetable',
            name='personaltimetable_ptr',
        ),
        migrations.RemoveField(
            model_name='uoftpersonaltimetable',
            name='course_offerings',
        ),
        migrations.RemoveField(
            model_name='uoftpersonaltimetable',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='uoftpersonaltimetable',
            name='personaltimetable_ptr',
        ),
        migrations.AddField(
            model_name='personaltimetable',
            name='courses',
            field=models.ManyToManyField(to='timetable.Course'),
        ),
    ]
