# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-12 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaltimetable',
            old_name='semester',
            new_name='_semester',
        ),
    ]
