# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_customslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customslot',
            name='day',
            field=models.CharField(default='R', max_length=1),
            preserve_default=False,
        ),
    ]
