# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20160517_1652'),
        ('timetable', '0039_auto_20160517_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltimetable',
            name='sections',
            field=models.ManyToManyField(to='timetable.Section'),
        ),
        migrations.DeleteModel(
            name='HopkinsPersonalTimetable',
        ),
        migrations.DeleteModel(
            name='RutgersPersonalTimetable',
        ),
        migrations.DeleteModel(
            name='UmdPersonalTimetable',
        ),
        migrations.DeleteModel(
            name='UofTPersonalTimetable',
        ),
    ]
