# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-18 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtm', '0002_auto_20170218_1542'),
        ('student', '0015_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.NullBooleanField(default=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtm.GoogleCalendar')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='calendar_preferences',
            field=models.ManyToManyField(blank=True, to='student.CalendarPreference'),
        ),
    ]
