# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-24 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20170223_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaltimetable',
            old_name='semester',
            new_name='_semester',
        ),
    ]
