# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-24 21:20
from __future__ import unicode_literals
from operator import attrgetter

from django.db import migrations, models
import django.db.models.deletion

from update_semester_field import update_sem_fields


def update_student_semesters(apps, schema_editor):
    tables_to_update = [apps.get_model('student', 'PersonalTimetable')]
    for table in tables_to_update:
        update_sem_fields(table, get_school=attrgetter('school'), 
                        sem_table=apps.get_model('timetable', 'Sem'))


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_section_semester'),
        ('student', '0017_auto_20170224_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltimetable',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.Semester'),
            preserve_default=False,
        ),
        migrations.RunPython(update_student_semesters)
    ]
