# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-08 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_update_semester_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='time_accepted_tos',
            field=models.DateTimeField(null=True),
        ),
    ]
