# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-25 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_personaltimetable_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltimetable',
            name='sem_name',
        ),
        migrations.RemoveField(
            model_name='personaltimetable',
            name='year',
        ),
    ]
