# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-24 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_finalexamshare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalexamshare',
            name='student',
        ),
        migrations.DeleteModel(
            name='FinalExamShare',
        ),
    ]
