# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-20 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_student_time_accepted_tos'),
        ('student', '0019_add_custom_slots'),
    ]

    operations = [
    ]
