# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-15 23:35


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_student_time_accepted_tos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltimetable',
            name='_semester',
        ),
    ]
