# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-17 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_remove_personaltimetable_time_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='title',
            field=models.CharField(choices=[('FIRE', 'FIRE'), ('LOVE', 'LOVE'), ('CRAP', 'CRAP'), ('OKAY', 'OKAY'), ('BORING', 'BORING'), ('HARD', 'HARD'), ('EASY', 'EASY'), ('INTERESTING', 'INTERESTING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationtoken',
            name='auth',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationtoken',
            name='endpoint',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationtoken',
            name='p256dh',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='fbook_uid',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(default='', max_length=255),
        ),
    ]
