# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-11-19 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_remove_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hopid',
            field=models.CharField(default=b'', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='jhed',
            field=models.CharField(default=b'', max_length=10, null=True),
        )
    ]
