# Generated by Django 2.2.18 on 2021-02-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_remove_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltimetable',
            name='has_conflict',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='title',
            field=models.CharField(choices=[('FIRE', 'FIRE'), ('LOVE', 'LOVE'), ('CRAP', 'CRAP'), ('OKAY', 'OKAY'), ('BORING', 'BORING'), ('HARD', 'HARD'), ('EASY', 'EASY'), ('INTERESTING', 'INTERESTING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationtoken',
            name='auth',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationtoken',
            name='endpoint',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationtoken',
            name='p256dh',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='fbook_uid',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(default='', max_length=255),
        ),
    ]
