# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-04-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_remove_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPersonalTimetable',
            fields=[
                ('personaltimetable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.PersonalTimetable')),
                ('year_of_study', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('student.personaltimetable',),
        ),
    ]
