# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-05-04 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20190407_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sub_school',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
