# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-05-04 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_student_sub_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sis_enabled',
            field=models.NullBooleanField(default=False),
        ),
    ]
