# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-05-10 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_personaltimetable_is_official'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltimetable',
            name='is_official',
        ),
    ]
