# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-01-11 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_pilotoffering'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotoffering',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
