# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-01-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_auto_20200115_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='disabilities',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=b'', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=b'', max_length=255, null=True),
        ),
    ]
