# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-01-26 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_auto_20200126_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pilot_registration',
            field=models.NullBooleanField(default=False),
        ),
    ]
