# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-01-27 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_auto_20200126_1700'),
    ]

    operations = [
    ]
