# Generated by Django 3.1 on 2021-09-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20210724_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='disabilities',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='emails_enabled',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pre_health',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='social_all',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='social_courses',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='social_offerings',
            field=models.BooleanField(null=True),
        ),
    ]
