# Generated by Django 2.2.18 on 2021-06-21 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20170910_2155'),
        ('student', '0034_merge'),
    ]

    operations = [
    ]
