# Generated by Django 3.2.10 on 2021-12-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0035_alter_student_jhed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PilotOffering",
        ),
    ]
