# Generated by Django 3.2.10 on 2021-12-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0036_delete_pilotoffering"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalevent",
            name="timetable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.personaltimetable",
            ),
        ),
    ]
