# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0033_section_course_section_id'),
        ('student', '0036_auto_20210410_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sis_registered_courses',
        ),
        migrations.AddField(
            model_name='student',
            name='sis_registered_sections',
            field=models.ManyToManyField(to='timetable.Section'),
        ),
    ]
