# Generated by Django 3.2.7 on 2022-01-17 01:46

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("student", "0037_personalevent_timetable"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE student_personalevent SET timetable_id = personaltimetable_id FROM student_personaltimetable_events WHERE student_personaltimetable_events.personalevent_id = student_personalevent.id;"
        )
    ]
