# Generated by Django 3.2.10 on 2021-12-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_change_pe_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltimetable',
            name='events',
        ),
    ]
