# Generated by Django 3.2.7 on 2022-01-17 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0038_event_to_foreign_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personaltimetable",
            name="events",
        ),
        migrations.AlterField(
            model_name="personalevent",
            name="timetable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="student.personaltimetable",
            ),
        ),
    ]
