# Generated by Django 3.2.10 on 2021-12-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0039_remove_personaltimetable_events"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="disabilities",
        ),
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="hopid",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="pre_health",
        ),
        migrations.AlterField(
            model_name="personalevent",
            name="timetable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="student.personaltimetable",
            ),
        ),
    ]
