# Generated by Django 3.2.10 on 2021-12-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0039_auto_20220116_2050"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="disabilities",
        ),
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="hopid",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="pre_health",
        ),
    ]
