# Generated by Django 3.2.7 on 2022-02-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_student_preferred_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltimetable',
            name='show_weekend',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
