# Generated by Django 3.2.12 on 2022-10-20 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0043_personaltimetable_show_weekend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='integrations',
        ),
    ]
