# Generated by Django 3.2.12 on 2022-12-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0044_remove_student_integrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaltimetable",
            name="show_weekend",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
