# Generated by Django 3.2.12 on 2023-02-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0045_alter_personaltimetable_show_weekend"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RegistrationToken",
        ),
    ]
