# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-18 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0015_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateTimeField()),
                ('gcal_ids', models.TextField(default='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
