# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-18 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtm', '0002_auto_20170218_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleShare',
            new_name='AvailabilityShare',
        ),
    ]
