# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-23 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtm', '0003_auto_20170218_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityshare',
            name='expiry',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
