/**
Copyright (C) 2017 Semester.ly Technologies, LLC

Semester.ly is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Semester.ly is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
**/

/* eslint-disable no-useless-escape */

const courseModalBodyFixture = {
  schoolSpecificInfo: {
    primaryDisplay: 'name',
    areasName: 'Areas',
    departmentsName: 'Departments',
    levelsName: 'Levels',
    timesName: 'Times',
    courseRegex: '([A-Z]{2}\\.\\d{3}\\.\\d{3})',
    campuses: {
      1: '',
    },
  },
  addOrRemoveCourse: () => null,
  react: () => null,
  hideModal: () => null,
  openSignUpModal: () => null,
  changeUserInfo: () => null,
  saveSettings: () => null,
  hoverSection: () => null,
  unHoverSection: () => null,
  fetchCourseInfo: () => null,
  isSectionLocked: () => null,
  isSectionOnActiveTimetable: () => null,
  getShareLink: () => null,
  getShareLinkFromModal: () => null,
  isFetching: false,
  isFetchingClassmates: false,
  data: {
    evals: [
      {
        professor: 'Nitya\u00a0Kitchloo\u00a0',
        summary: 'The best\u00a0aspect\u00a0of\u00a0this\u00a0course was\u00a0professor\u2019s\u00a0clear\u00a0and\u00a0effective\u00a0teaching\u00a0style.\u00a0The professor\u00a0also\u00a0taught almost\u00a0directly\u00a0from\u00a0the textbook,\u00a0which\u00a0made\u00a0it\u00a0easy\u00a0for students\u00a0to\u00a0follow\u00a0along\u00a0and\u00a0review\u00a0the\u00a0math\u00a0problems.\u00a0The\u00a0worst\u00a0aspects\u00a0of\u00a0the\u00a0course\u00a0included\u00a0the\u00a0large\u00a0amounts\u00a0of\u00a0information\u00a0that\u00a0students\u00a0had\u00a0to\u00a0learn,\u00a0and\u00a0the\u00a0occasional\u00a0confusion\u00a0about\u00a0the\u00a0content\u00a0as\u00a0the\u00a0professor\u00a0sometimes\u00a0made\u00a0topics\u00a0more\u00a0complicated\u00a0than\u00a0necessary.\u00a0Many\u00a0students\u00a0also\u00a0felt that\u00a0the\u00a0class\u00a0sessions\u00a0with\u00a0the\u00a0teaching\u00a0assistants\u00a0were\u00a0not\u00a0very\u00a0helpful.\u00a0The\u00a0course\u00a0would\u00a0improve\u00a0if the\u00a0professor\u00a0went\u00a0over\u00a0more\u00a0problems\u00a0and\u00a0examples\u00a0during\u00a0lectures,\u00a0and\u00a0it\u00a0would\u00a0also\u00a0improve\u00a0if\u00a0the\u00a0students\u00a0were completely\u00a0clear\u00a0on\u00a0the\u00a0type\u00a0of\u00a0problems\u00a0that\u00a0would\u00a0be\u00a0on\u00a0exams.\u00a0Prospective\u00a0students\u00a0should\u00a0be\u00a0conscious\u00a0of\u00a0completing\u00a0their homework\u00a0and\u00a0must\u00a0be\u00a0very\u00a0familiar\u00a0with\u00a0Calculus\u00a0I\u00a0in\u00a0order to\u00a0perform\u00a0well in\u00a0this\u00a0somewhat\u00a0difficult course.\u00a0\u00a0',
        course: 411,
        score: 3.26,
        year: 'Fall:2012',
        course_code: 'AS.110.106.01-11\u00a0',
        id: 550,
      },
      {
        professor: 'Jose\u00a0Gomez\u00a0',
        summary: 'Students\u00a0praised\u00a0this\u00a0course\u00a0and\u00a0its\u00a0professor\u00a0for\u00a0effectively\u00a0going\u00a0through\u00a0a\u00a0lot\u00a0of\u00a0material in\u00a0a single\u00a0semester.\u00a0Students\u00a0also\u00a0appreciated\u00a0the fact that there were\u00a0various\u00a0resources\u00a0they\u00a0could\u00a0turn\u00a0to\u00a0for\u00a0help\u00a0with\u00a0the\u00a0math\u00a0such\u00a0as\u00a0Learning\u00a0Den\u00a0and\u00a0PILOT.\u00a0However,\u00a0some students\u00a0said\u00a0lectures\u00a0were\u00a0hard\u00a0to\u00a0fol\u00a0ow\u00a0and\u00a0rushed.\u00a0Multiple\u00a0students\u00a0also\u00a0found\u00a0the\u00a0instructor\u00a0to\u00a0be,\u00a0at times,\u00a0sarcastic\u00a0with\u00a0students.\u00a0Suggestions\u00a0to\u00a0improve\u00a0the\u00a0course\u00a0included\u00a0adding\u00a0more exams\u00a0or\u00a0other\u00a0graded\u00a0opportunities.\u00a0Other\u00a0students\u00a0wanted\u00a0to\u00a0have\u00a0lecture\u00a0notes\u00a0or\u00a0a recording\u00a0of each\u00a0class\u00a0lecture\u00a0available\u00a0online.\u00a0Prior\u00a0knowledge\u00a0of\u00a0Calculus\u00a0was\u00a0helpful\u00a0but\u00a0not\u00a0necessary\u00a0for\u00a0success\u00a0in\u00a0the\u00a0course.\u00a0Students\u00a0found\u00a0staying\u00a0on\u00a0top\u00a0of\u00a0homework,\u00a0studying and\u00a0asking questions\u00a0were\u00a0also\u00a0important\u00a0for doing\u00a0well in\u00a0this\u00a0course.\u00a0\u00a0',
        course: 411,
        score: 3.84,
        year: 'Fall:2013',
        course_code: 'AS.110.106.01-11\u00a0',
        id: 1124,
      },
      {
        professor: 'Zhan Li\u00a0',
        summary: 'Students\u00a0praised\u00a0this\u00a0course\u00a0for\u00a0having a\u00a0manageable\u00a0amount\u00a0of\u00a0homework\u00a0and\u00a0how\u00a0the\u00a0instructor\u00a0seemed\u00a0committed\u00a0to\u00a0making sure\u00a0students\u00a0succeeded.\u00a0Perceived\u00a0issues\u00a0with\u00a0the\u00a0course\u00a0included\u00a0a\u00a0belief\u00a0by\u00a0multiple\u00a0students\u00a0that\u00a0the\u00a0course\u2019s\u00a0instructor\u00a0was\u00a0hard\u00a0to\u00a0understand\u00a0and\u00a0in\u00a0addition,\u00a0tended\u00a0to\u00a0rush\u00a0through\u00a0certain\u00a0ideas\u00a0presumably\u00a0because\u00a0he\u00a0assumed\u00a0students\u00a0were\u00a0already\u00a0familiar with\u00a0them.\u00a0Suggestions\u00a0for\u00a0improvement\u00a0included\u00a0a\u00a0desire\u00a0by\u00a0multiple\u00a0students\u00a0for\u00a0a\u00a0more\u00a0eloquent\u00a0instructor\u00a0and\u00a0for\u00a0the\u00a0course\u00a0to\u00a0be\u00a0more\u00a0interactive,\u00a0partly\u00a0so\u00a0the\u00a0instructor could\u00a0better\u00a0gauge how\u00a0well\u00a0students\u00a0were\u00a0grasping\u00a0topics.\u00a0Prospective\u00a0students\u00a0should\u00a0know\u00a0that\u00a0students\u00a0found\u00a0the\u00a0course\u00a0was\u00a0chal\u00a0enging and\u00a0that\u00a0those\u00a0who\u00a0had\u00a0a\u00a0background\u00a0in\u00a0the\u00a0subject\u00a0found\u00a0the\u00a0course\u00a0to\u00a0be\u00a0easier.\u00a0\u00a0',
        course: 411,
        score: 3.57,
        year: 'Fall:2014',
        course_code: 'AS.110.106.01-11\u00a0',
        id: 1740,
      },
      {
        professor: 'Nicholas\u00a0Marshburn\u00a0',
        summary: 'The best\u00a0aspects\u00a0of\u00a0the course were\u00a0the amazing\u00a0teaching\u00a0assistants\u00a0and\u00a0the\u00a0helpful\u00a0professor who\u00a0was\u00a0able\u00a0to\u00a0explain\u00a0the concepts\u00a0to\u00a0students\u00a0very\u00a0well.\u00a0The\u00a0worst aspects\u00a0of\u00a0the\u00a0course were\u00a0the\u00a0very\u00a0lengthy\u00a0homework\u00a0assignments\u00a0and\u00a0the\u00a0feedback\u00a0students\u00a0received\u00a0on\u00a0them.\u00a0The\u00a0lectures\u00a0were\u00a0dul\u00a0\u00a0and\u00a0often\u00a0unclear\u00a0and\u00a0many\u00a0didn\u2019t\u00a0find\u00a0the\u00a0teaching assistants\u00a0very\u00a0helpful.\u00a0The\u00a0course\u00a0would\u00a0improve\u00a0if\u00a0the\u00a0lectures\u00a0were\u00a0more\u00a0engaging,\u00a0if\u00a0there\u00a0were fewer\u00a0homework\u00a0assignments,\u00a0and\u00a0if homework\u00a0was\u00a0reviewed.\u00a0Prospective\u00a0students\u00a0should\u00a0endeavor\u00a0to\u00a0attend\u00a0al\u00a0\u00a0lectures\u00a0and\u00a0stay\u00a0on\u00a0top\u00a0of\u00a0the homework\u00a0assignments\u00a0to\u00a0be\u00a0successful\u00a0in\u00a0the\u00a0course.\u00a0\u00a0',
        course: 411,
        score: 4.14,
        year: 'Spring:2013',
        course_code: 'AS.110.106.01-03\u00a0',
        id: 2179,
      },
      {
        professor: 'Richard Brown\u00a0',
        summary: 'According\u00a0to\u00a0students,\u00a0the\u00a0professor\u00a0of this\u00a0course\u00a0did\u00a0a commendable\u00a0job\u00a0of\u00a0explaining\u00a0the\u00a0theory,\u00a0formulas\u00a0and\u00a0concepts\u00a0of\u00a0study.\u00a0He\u00a0always\u00a0began\u00a0class\u00a0asking if\u00a0students\u00a0had\u00a0questions,\u00a0and\u00a0it\u00a0was\u00a0obvious\u00a0that\u00a0he\u00a0cared\u00a0about\u00a0his\u00a0students\u00a0grasping\u00a0the\u00a0material.\u00a0The\u00a0amount\u00a0of\u00a0work\u00a0required\u00a0for\u00a0problem\u00a0sets\u00a0was\u00a0overwhelming and\u00a0the\u00a0homework\u00a0and\u00a0exams\u00a0were\u00a0complicated.\u00a0Many\u00a0students\u00a0agreed\u00a0that\u00a0the homework\u00a0was\u00a0weighted\u00a0too\u00a0heavily,\u00a0and\u00a0that it should\u2019ve been\u00a0used\u00a0as\u00a0a\u00a0learning\u00a0tool\u00a0instead\u00a0of\u00a0a\u00a0way\u00a0to\u00a0decrease\u00a0grades.\u00a0Suggestions\u00a0for\u00a0improvement\u00a0include:\u00a0cutting down\u00a0on\u00a0homework,\u00a0easier __tests__,\u00a0and\u00a0more\u00a0time\u00a0to\u00a0review\u00a0material.\u00a0Prospective\u00a0students\u00a0should\u00a0prepare\u00a0for a demanding\u00a0work\u00a0load.\u00a0\u00a0',
        course: 411,
        score: 4.16,
        year: 'Spring:2014',
        course_code: 'AS.110.106.01-03\u00a0',
        id: 2779,
      },
      {
        professor: 'Zhan Li\u00a0',
        summary: 'The best\u00a0aspects\u00a0of\u00a0this\u00a0class\u00a0were the structured\u00a0lectures\u00a0and\u00a0relatively\u00a0smal\u00a0\u00a0class\u00a0size.\u00a0\u00a0Many\u00a0students\u00a0agreed\u00a0that\u00a0the\u00a0professor\u00a0was\u00a0very\u00a0approachable\u00a0and\u00a0helpful,\u00a0and\u00a0that he\u00a0made\u00a0an\u00a0effort to\u00a0ensure that\u00a0students\u00a0understood\u00a0the\u00a0material.\u00a0\u00a0Some\u00a0students\u00a0found\u00a0that the\u00a0class\u00a0moved\u00a0too\u00a0quickly\u00a0through\u00a0material and\u00a0that\u00a0there were occasional\u00a0disconnects\u00a0between\u00a0lecture\u00a0topics\u00a0and\u00a0TA\u00a0sections.\u00a0\u00a0This class\u00a0could\u00a0be\u00a0improved\u00a0by\u00a0better\u00a0matching\u00a0the\u00a0difficulty\u00a0of homework\u00a0to\u00a0exams.\u00a0\u00a0Prospective students\u00a0should\u00a0have\u00a0a\u00a0strong\u00a0background\u00a0in\u00a0trigonometry.\u00a0',
        course: 411,
        score: 3.67,
        year: 'Spring:2015',
        course_code: 'AS.110.106.01-02\u00a0',
        id: 3445,
      },
    ],
    reactions: [

    ],
    code: 'AS.110.106',
    num_credits: 4,
    description: 'Differential and integral calculus. Includes analytic geometry, functions, limits, integrals and\r\nderivatives, introduction to differential equations, functions of several variables, linear systems,\r\napplications for systems of linear differential equations, probability distributions. Many\r\napplications to the biological and social sciences will be discussed.',
    prerequisites: '',
    areas: 'Q',
    eval_info: [
      {
        professor: 'Zhan Li\u00a0',
        summary: 'The best\u00a0aspects\u00a0of\u00a0this\u00a0class\u00a0were the structured\u00a0lectures\u00a0and\u00a0relatively\u00a0smal\u00a0\u00a0class\u00a0size.\u00a0\u00a0Many\u00a0students\u00a0agreed\u00a0that\u00a0the\u00a0professor\u00a0was\u00a0very\u00a0approachable\u00a0and\u00a0helpful,\u00a0and\u00a0that he\u00a0made\u00a0an\u00a0effort to\u00a0ensure that\u00a0students\u00a0understood\u00a0the\u00a0material.\u00a0\u00a0Some\u00a0students\u00a0found\u00a0that the\u00a0class\u00a0moved\u00a0too\u00a0quickly\u00a0through\u00a0material and\u00a0that\u00a0there were occasional\u00a0disconnects\u00a0between\u00a0lecture\u00a0topics\u00a0and\u00a0TA\u00a0sections.\u00a0\u00a0This class\u00a0could\u00a0be\u00a0improved\u00a0by\u00a0better\u00a0matching\u00a0the\u00a0difficulty\u00a0of homework\u00a0to\u00a0exams.\u00a0\u00a0Prospective students\u00a0should\u00a0have\u00a0a\u00a0strong\u00a0background\u00a0in\u00a0trigonometry.\u00a0',
        course: 411,
        score: 3.67,
        year: 'Spring:2015',
        course_code: 'AS.110.106.01-02\u00a0',
        id: 3445,
        unique_term_year: true,
      },
      {
        professor: 'Zhan Li\u00a0',
        summary: 'Students\u00a0praised\u00a0this\u00a0course\u00a0for\u00a0having a\u00a0manageable\u00a0amount\u00a0of\u00a0homework\u00a0and\u00a0how\u00a0the\u00a0instructor\u00a0seemed\u00a0committed\u00a0to\u00a0making sure\u00a0students\u00a0succeeded.\u00a0Perceived\u00a0issues\u00a0with\u00a0the\u00a0course\u00a0included\u00a0a\u00a0belief\u00a0by\u00a0multiple\u00a0students\u00a0that\u00a0the\u00a0course\u2019s\u00a0instructor\u00a0was\u00a0hard\u00a0to\u00a0understand\u00a0and\u00a0in\u00a0addition,\u00a0tended\u00a0to\u00a0rush\u00a0through\u00a0certain\u00a0ideas\u00a0presumably\u00a0because\u00a0he\u00a0assumed\u00a0students\u00a0were\u00a0already\u00a0familiar with\u00a0them.\u00a0Suggestions\u00a0for\u00a0improvement\u00a0included\u00a0a\u00a0desire\u00a0by\u00a0multiple\u00a0students\u00a0for\u00a0a\u00a0more\u00a0eloquent\u00a0instructor\u00a0and\u00a0for\u00a0the\u00a0course\u00a0to\u00a0be\u00a0more\u00a0interactive,\u00a0partly\u00a0so\u00a0the\u00a0instructor could\u00a0better\u00a0gauge how\u00a0well\u00a0students\u00a0were\u00a0grasping\u00a0topics.\u00a0Prospective\u00a0students\u00a0should\u00a0know\u00a0that\u00a0students\u00a0found\u00a0the\u00a0course\u00a0was\u00a0chal\u00a0enging and\u00a0that\u00a0those\u00a0who\u00a0had\u00a0a\u00a0background\u00a0in\u00a0the\u00a0subject\u00a0found\u00a0the\u00a0course\u00a0to\u00a0be\u00a0easier.\u00a0\u00a0',
        course: 411,
        score: 3.57,
        year: 'Fall:2014',
        course_code: 'AS.110.106.01-11\u00a0',
        id: 1740,
        unique_term_year: true,
      },
      {
        professor: 'Richard Brown\u00a0',
        summary: 'According\u00a0to\u00a0students,\u00a0the\u00a0professor\u00a0of this\u00a0course\u00a0did\u00a0a commendable\u00a0job\u00a0of\u00a0explaining\u00a0the\u00a0theory,\u00a0formulas\u00a0and\u00a0concepts\u00a0of\u00a0study.\u00a0He\u00a0always\u00a0began\u00a0class\u00a0asking if\u00a0students\u00a0had\u00a0questions,\u00a0and\u00a0it\u00a0was\u00a0obvious\u00a0that\u00a0he\u00a0cared\u00a0about\u00a0his\u00a0students\u00a0grasping\u00a0the\u00a0material.\u00a0The\u00a0amount\u00a0of\u00a0work\u00a0required\u00a0for\u00a0problem\u00a0sets\u00a0was\u00a0overwhelming and\u00a0the\u00a0homework\u00a0and\u00a0exams\u00a0were\u00a0complicated.\u00a0Many\u00a0students\u00a0agreed\u00a0that\u00a0the homework\u00a0was\u00a0weighted\u00a0too\u00a0heavily,\u00a0and\u00a0that it should\u2019ve been\u00a0used\u00a0as\u00a0a\u00a0learning\u00a0tool\u00a0instead\u00a0of\u00a0a\u00a0way\u00a0to\u00a0decrease\u00a0grades.\u00a0Suggestions\u00a0for\u00a0improvement\u00a0include:\u00a0cutting down\u00a0on\u00a0homework,\u00a0easier __tests__,\u00a0and\u00a0more\u00a0time\u00a0to\u00a0review\u00a0material.\u00a0Prospective\u00a0students\u00a0should\u00a0prepare\u00a0for a demanding\u00a0work\u00a0load.\u00a0\u00a0',
        course: 411,
        score: 4.16,
        year: 'Spring:2014',
        course_code: 'AS.110.106.01-03\u00a0',
        id: 2779,
        unique_term_year: true,
      },
      {
        professor: 'Jose\u00a0Gomez\u00a0',
        summary: 'Students\u00a0praised\u00a0this\u00a0course\u00a0and\u00a0its\u00a0professor\u00a0for\u00a0effectively\u00a0going\u00a0through\u00a0a\u00a0lot\u00a0of\u00a0material in\u00a0a single\u00a0semester.\u00a0Students\u00a0also\u00a0appreciated\u00a0the fact that there were\u00a0various\u00a0resources\u00a0they\u00a0could\u00a0turn\u00a0to\u00a0for\u00a0help\u00a0with\u00a0the\u00a0math\u00a0such\u00a0as\u00a0Learning\u00a0Den\u00a0and\u00a0PILOT.\u00a0However,\u00a0some students\u00a0said\u00a0lectures\u00a0were\u00a0hard\u00a0to\u00a0fol\u00a0ow\u00a0and\u00a0rushed.\u00a0Multiple\u00a0students\u00a0also\u00a0found\u00a0the\u00a0instructor\u00a0to\u00a0be,\u00a0at times,\u00a0sarcastic\u00a0with\u00a0students.\u00a0Suggestions\u00a0to\u00a0improve\u00a0the\u00a0course\u00a0included\u00a0adding\u00a0more exams\u00a0or\u00a0other\u00a0graded\u00a0opportunities.\u00a0Other\u00a0students\u00a0wanted\u00a0to\u00a0have\u00a0lecture\u00a0notes\u00a0or\u00a0a recording\u00a0of each\u00a0class\u00a0lecture\u00a0available\u00a0online.\u00a0Prior\u00a0knowledge\u00a0of\u00a0Calculus\u00a0was\u00a0helpful\u00a0but\u00a0not\u00a0necessary\u00a0for\u00a0success\u00a0in\u00a0the\u00a0course.\u00a0Students\u00a0found\u00a0staying\u00a0on\u00a0top\u00a0of\u00a0homework,\u00a0studying and\u00a0asking questions\u00a0were\u00a0also\u00a0important\u00a0for doing\u00a0well in\u00a0this\u00a0course.\u00a0\u00a0',
        course: 411,
        score: 3.84,
        year: 'Fall:2013',
        course_code: 'AS.110.106.01-11\u00a0',
        id: 1124,
        unique_term_year: true,
      },
      {
        professor: 'Nicholas\u00a0Marshburn\u00a0',
        summary: 'The best\u00a0aspects\u00a0of\u00a0the course were\u00a0the amazing\u00a0teaching\u00a0assistants\u00a0and\u00a0the\u00a0helpful\u00a0professor who\u00a0was\u00a0able\u00a0to\u00a0explain\u00a0the concepts\u00a0to\u00a0students\u00a0very\u00a0well.\u00a0The\u00a0worst aspects\u00a0of\u00a0the\u00a0course were\u00a0the\u00a0very\u00a0lengthy\u00a0homework\u00a0assignments\u00a0and\u00a0the\u00a0feedback\u00a0students\u00a0received\u00a0on\u00a0them.\u00a0The\u00a0lectures\u00a0were\u00a0dul\u00a0\u00a0and\u00a0often\u00a0unclear\u00a0and\u00a0many\u00a0didn\u2019t\u00a0find\u00a0the\u00a0teaching assistants\u00a0very\u00a0helpful.\u00a0The\u00a0course\u00a0would\u00a0improve\u00a0if\u00a0the\u00a0lectures\u00a0were\u00a0more\u00a0engaging,\u00a0if\u00a0there\u00a0were fewer\u00a0homework\u00a0assignments,\u00a0and\u00a0if homework\u00a0was\u00a0reviewed.\u00a0Prospective\u00a0students\u00a0should\u00a0endeavor\u00a0to\u00a0attend\u00a0al\u00a0\u00a0lectures\u00a0and\u00a0stay\u00a0on\u00a0top\u00a0of\u00a0the homework\u00a0assignments\u00a0to\u00a0be\u00a0successful\u00a0in\u00a0the\u00a0course.\u00a0\u00a0',
        course: 411,
        score: 4.14,
        year: 'Spring:2013',
        course_code: 'AS.110.106.01-03\u00a0',
        id: 2179,
        unique_term_year: true,
      },
      {
        professor: 'Nitya\u00a0Kitchloo\u00a0',
        summary: 'The best\u00a0aspect\u00a0of\u00a0this\u00a0course was\u00a0professor\u2019s\u00a0clear\u00a0and\u00a0effective\u00a0teaching\u00a0style.\u00a0The professor\u00a0also\u00a0taught almost\u00a0directly\u00a0from\u00a0the textbook,\u00a0which\u00a0made\u00a0it\u00a0easy\u00a0for students\u00a0to\u00a0follow\u00a0along\u00a0and\u00a0review\u00a0the\u00a0math\u00a0problems.\u00a0The\u00a0worst\u00a0aspects\u00a0of\u00a0the\u00a0course\u00a0included\u00a0the\u00a0large\u00a0amounts\u00a0of\u00a0information\u00a0that\u00a0students\u00a0had\u00a0to\u00a0learn,\u00a0and\u00a0the\u00a0occasional\u00a0confusion\u00a0about\u00a0the\u00a0content\u00a0as\u00a0the\u00a0professor\u00a0sometimes\u00a0made\u00a0topics\u00a0more\u00a0complicated\u00a0than\u00a0necessary.\u00a0Many\u00a0students\u00a0also\u00a0felt that\u00a0the\u00a0class\u00a0sessions\u00a0with\u00a0the\u00a0teaching\u00a0assistants\u00a0were\u00a0not\u00a0very\u00a0helpful.\u00a0The\u00a0course\u00a0would\u00a0improve\u00a0if the\u00a0professor\u00a0went\u00a0over\u00a0more\u00a0problems\u00a0and\u00a0examples\u00a0during\u00a0lectures,\u00a0and\u00a0it\u00a0would\u00a0also\u00a0improve\u00a0if\u00a0the\u00a0students\u00a0were completely\u00a0clear\u00a0on\u00a0the\u00a0type\u00a0of\u00a0problems\u00a0that\u00a0would\u00a0be\u00a0on\u00a0exams.\u00a0Prospective\u00a0students\u00a0should\u00a0be\u00a0conscious\u00a0of\u00a0completing\u00a0their homework\u00a0and\u00a0must\u00a0be\u00a0very\u00a0familiar\u00a0with\u00a0Calculus\u00a0I\u00a0in\u00a0order to\u00a0perform\u00a0well in\u00a0this\u00a0somewhat\u00a0difficult course.\u00a0\u00a0',
        course: 411,
        score: 3.26,
        year: 'Fall:2012',
        course_code: 'AS.110.106.01-11\u00a0',
        id: 550,
        unique_term_year: true,
      },
    ],
    integrations: [

    ],
    id: 411,
    textbooks: [

    ],
    popularity_percent: 0.011111111111111,
    related_courses: [

    ],
    department: 'AS Mathematics',
    regexed_courses: {

    },
    exclusions: '',
    sections: {
      L: {
        '(07)': [
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1076,
            size: 30,
            time_start: '11:00',
            meeting_section: '(07)',
            section: 1076,
            section_type: 'L',
            enrolment: 0,
            day: 'F',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1076,
            size: 30,
            time_start: '11:00',
            meeting_section: '(07)',
            section: 1076,
            section_type: 'L',
            enrolment: 0,
            day: 'M',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '15:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1076,
            size: 30,
            time_start: '15:00',
            meeting_section: '(07)',
            section: 1076,
            section_type: 'L',
            enrolment: 0,
            day: 'R',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1076,
            size: 30,
            time_start: '11:00',
            meeting_section: '(07)',
            section: 1076,
            section_type: 'L',
            enrolment: 0,
            day: 'W',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
        ],
        '(06)': [
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '17:20',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1075,
            size: 30,
            time_start: '16:30',
            meeting_section: '(06)',
            section: 1075,
            section_type: 'L',
            enrolment: 0,
            day: 'R',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1075,
            size: 30,
            time_start: '11:00',
            meeting_section: '(06)',
            section: 1075,
            section_type: 'L',
            enrolment: 0,
            day: 'F',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1075,
            size: 30,
            time_start: '11:00',
            meeting_section: '(06)',
            section: 1075,
            section_type: 'L',
            enrolment: 0,
            day: 'W',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1075,
            size: 30,
            time_start: '11:00',
            meeting_section: '(06)',
            section: 1075,
            section_type: 'L',
            enrolment: 0,
            day: 'M',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
        ],
        '(04)': [
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '15:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1073,
            size: 30,
            time_start: '15:00',
            meeting_section: '(04)',
            section: 1073,
            section_type: 'L',
            enrolment: 0,
            day: 'R',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '10:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1073,
            size: 30,
            time_start: '10:00',
            meeting_section: '(04)',
            section: 1073,
            section_type: 'L',
            enrolment: 0,
            day: 'F',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '10:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1073,
            size: 30,
            time_start: '10:00',
            meeting_section: '(04)',
            section: 1073,
            section_type: 'L',
            enrolment: 0,
            day: 'M',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '10:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1073,
            size: 30,
            time_start: '10:00',
            meeting_section: '(04)',
            section: 1073,
            section_type: 'L',
            enrolment: 0,
            day: 'W',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
        ],
        '(05)': [
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '14:20',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1074,
            size: 30,
            time_start: '13:30',
            meeting_section: '(05)',
            section: 1074,
            section_type: 'L',
            enrolment: 0,
            day: 'R',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1074,
            size: 30,
            time_start: '11:00',
            meeting_section: '(05)',
            section: 1074,
            section_type: 'L',
            enrolment: 0,
            day: 'F',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1074,
            size: 30,
            time_start: '11:00',
            meeting_section: '(05)',
            section: 1074,
            section_type: 'L',
            enrolment: 0,
            day: 'W',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1074,
            size: 30,
            time_start: '11:00',
            meeting_section: '(05)',
            section: 1074,
            section_type: 'L',
            enrolment: 0,
            day: 'M',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
        ],
        '(03)': [
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '17:20',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1072,
            size: 30,
            time_start: '16:30',
            meeting_section: '(03)',
            section: 1072,
            section_type: 'L',
            enrolment: 0,
            day: 'R',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '10:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1072,
            size: 30,
            time_start: '10:00',
            meeting_section: '(03)',
            section: 1072,
            section_type: 'L',
            enrolment: 0,
            day: 'F',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '10:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1072,
            size: 30,
            time_start: '10:00',
            meeting_section: '(03)',
            section: 1072,
            section_type: 'L',
            enrolment: 0,
            day: 'W',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '10:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1072,
            size: 30,
            time_start: '10:00',
            meeting_section: '(03)',
            section: 1072,
            section_type: 'L',
            enrolment: 0,
            day: 'M',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
        ],
        '(08)': [
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '15:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1077,
            size: 30,
            time_start: '15:00',
            meeting_section: '(08)',
            section: 1077,
            section_type: 'L',
            enrolment: 0,
            day: 'T',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1077,
            size: 30,
            time_start: '11:00',
            meeting_section: '(08)',
            section: 1077,
            section_type: 'L',
            enrolment: 0,
            day: 'F',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1077,
            size: 30,
            time_start: '11:00',
            meeting_section: '(08)',
            section: 1077,
            section_type: 'L',
            enrolment: 0,
            day: 'W',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1077,
            size: 30,
            time_start: '11:00',
            meeting_section: '(08)',
            section: 1077,
            section_type: 'L',
            enrolment: 0,
            day: 'M',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
        ],
        '(09)': [
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '14:20',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1078,
            size: 30,
            time_start: '13:30',
            meeting_section: '(09)',
            section: 1078,
            section_type: 'L',
            enrolment: 0,
            day: 'T',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1078,
            size: 30,
            time_start: '11:00',
            meeting_section: '(09)',
            section: 1078,
            section_type: 'L',
            enrolment: 0,
            day: 'F',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1078,
            size: 30,
            time_start: '11:00',
            meeting_section: '(09)',
            section: 1078,
            section_type: 'L',
            enrolment: 0,
            day: 'W',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '11:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1078,
            size: 30,
            time_start: '11:00',
            meeting_section: '(09)',
            section: 1078,
            section_type: 'L',
            enrolment: 0,
            day: 'M',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
        ],
        '(02)': [
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '15:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1071,
            size: 30,
            time_start: '15:00',
            meeting_section: '(02)',
            section: 1071,
            section_type: 'L',
            enrolment: 0,
            day: 'T',
            textbooks: [

            ],
            location: '',
            was_full: false,
            colourId: 0,
            code: 'AS.110.106',
            name: 'Calculus I (Biology and Social Sciences)',
            custom: false,
            num_conflicts: 1,
            shift_index: 0,
            depth_level: 0,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '10:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1071,
            size: 30,
            time_start: '10:00',
            meeting_section: '(02)',
            section: 1071,
            section_type: 'L',
            enrolment: 0,
            day: 'F',
            textbooks: [

            ],
            location: '',
            was_full: false,
            colourId: 0,
            code: 'AS.110.106',
            name: 'Calculus I (Biology and Social Sciences)',
            custom: false,
            num_conflicts: 2,
            shift_index: 1,
            depth_level: 0,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '10:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1071,
            size: 30,
            time_start: '10:00',
            meeting_section: '(02)',
            section: 1071,
            section_type: 'L',
            enrolment: 0,
            day: 'W',
            textbooks: [

            ],
            location: '',
            was_full: false,
            colourId: 0,
            code: 'AS.110.106',
            name: 'Calculus I (Biology and Social Sciences)',
            custom: false,
            num_conflicts: 2,
            shift_index: 1,
            depth_level: 0,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '10:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1071,
            size: 30,
            time_start: '10:00',
            meeting_section: '(02)',
            section: 1071,
            section_type: 'L',
            enrolment: 0,
            day: 'M',
            textbooks: [

            ],
            location: '',
            was_full: false,
            colourId: 0,
            code: 'AS.110.106',
            name: 'Calculus I (Biology and Social Sciences)',
            custom: false,
            num_conflicts: 2,
            shift_index: 1,
            depth_level: 0,
          },
        ],
        '(01)': [
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '17:20',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1070,
            size: 30,
            time_start: '16:30',
            meeting_section: '(01)',
            section: 1070,
            section_type: 'L',
            enrolment: 0,
            day: 'T',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '10:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1070,
            size: 30,
            time_start: '10:00',
            meeting_section: '(01)',
            section: 1070,
            section_type: 'L',
            enrolment: 0,
            day: 'F',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '10:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1070,
            size: 30,
            time_start: '10:00',
            meeting_section: '(01)',
            section: 1070,
            section_type: 'L',
            enrolment: 0,
            day: 'W',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
          {
            waitlist: -1,
            instructors: 'R. Brown',
            time_end: '10:50',
            waitlist_size: -1,
            course: 411,
            semester: 4,
            _semester: '',
            id: 1070,
            size: 30,
            time_start: '10:00',
            meeting_section: '(01)',
            section: 1070,
            section_type: 'L',
            enrolment: 0,
            day: 'M',
            textbooks: [

            ],
            location: '',
            was_full: false,
          },
        ],
      },
    },
    campus: '',
    name: 'Calculus I (Biology and Social Sciences)',
    section: '(02)',
  },
  classmates: {
    course_id: 411,
    past_classmates: [
      {
        major: 'Accounting',
        emails_enabled: true,
        school: 'jhu',
        sections: [
          '(01)',
        ],
        gender: 'female',
        social_offerings: true,
        class_year: 2018,
        social_all: true,
        last_name: 'Margolius Presler',
        integrations: [

        ],
        first_name: 'Linda',
        social_courses: true,
        img_url: 'https:\/\/scontent.xx.fbcdn.net\/v\/t1.0-1\/p50x50\/10957589_10152725992049147_2815259779743523470_n.jpg?oh=85550d1771fec7b1524ac1d9303cd697&oe=598CCC9B',
      },
    ],
    classmates: [
      {
        major: 'Accounting',
        emails_enabled: true,
        school: 'jhu',
        sections: [
          '(01)',
        ],
        gender: 'female',
        social_offerings: true,
        class_year: 2018,
        social_all: true,
        last_name: 'Margolius Presler',
        integrations: [

        ],
        first_name: 'Linda',
        social_courses: true,
        img_url: 'https:\/\/scontent.xx.fbcdn.net\/v\/t1.0-1\/p50x50\/10957589_10152725992049147_2815259779743523470_n.jpg?oh=85550d1771fec7b1524ac1d9303cd697&oe=598CCC9B',
      },
      {
        major: 'Accounting',
        emails_enabled: true,
        school: 'jhu',
        sections: [
          '(01)',
        ],
        gender: 'male',
        social_offerings: true,
        class_year: 2017,
        social_all: true,
        last_name: 'Isalwaysontheprowl',
        integrations: [

        ],
        first_name: 'Mylittlewilliamyao',
        social_courses: true,
        img_url: 'https:\/\/scontent.xx.fbcdn.net\/v\/t1.0-1\/c163.0.204.204\/s50x50\/12321414_113682579025974_6205266913524508520_n.jpg?oh=dfa9c89403c0179bd6b00e4afd300569&oe=599A0E58',
      },
    ],
  },
  id: 411,
  lectureSections: {
    '(07)': [
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1076,
        size: 30,
        time_start: '11:00',
        meeting_section: '(07)',
        section: 1076,
        section_type: 'L',
        enrolment: 0,
        day: 'F',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1076,
        size: 30,
        time_start: '11:00',
        meeting_section: '(07)',
        section: 1076,
        section_type: 'L',
        enrolment: 0,
        day: 'M',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '15:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1076,
        size: 30,
        time_start: '15:00',
        meeting_section: '(07)',
        section: 1076,
        section_type: 'L',
        enrolment: 0,
        day: 'R',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1076,
        size: 30,
        time_start: '11:00',
        meeting_section: '(07)',
        section: 1076,
        section_type: 'L',
        enrolment: 0,
        day: 'W',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
    ],
    '(06)': [
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '17:20',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1075,
        size: 30,
        time_start: '16:30',
        meeting_section: '(06)',
        section: 1075,
        section_type: 'L',
        enrolment: 0,
        day: 'R',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1075,
        size: 30,
        time_start: '11:00',
        meeting_section: '(06)',
        section: 1075,
        section_type: 'L',
        enrolment: 0,
        day: 'F',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1075,
        size: 30,
        time_start: '11:00',
        meeting_section: '(06)',
        section: 1075,
        section_type: 'L',
        enrolment: 0,
        day: 'W',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1075,
        size: 30,
        time_start: '11:00',
        meeting_section: '(06)',
        section: 1075,
        section_type: 'L',
        enrolment: 0,
        day: 'M',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
    ],
    '(04)': [
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '15:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1073,
        size: 30,
        time_start: '15:00',
        meeting_section: '(04)',
        section: 1073,
        section_type: 'L',
        enrolment: 0,
        day: 'R',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '10:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1073,
        size: 30,
        time_start: '10:00',
        meeting_section: '(04)',
        section: 1073,
        section_type: 'L',
        enrolment: 0,
        day: 'F',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '10:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1073,
        size: 30,
        time_start: '10:00',
        meeting_section: '(04)',
        section: 1073,
        section_type: 'L',
        enrolment: 0,
        day: 'M',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '10:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1073,
        size: 30,
        time_start: '10:00',
        meeting_section: '(04)',
        section: 1073,
        section_type: 'L',
        enrolment: 0,
        day: 'W',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
    ],
    '(05)': [
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '14:20',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1074,
        size: 30,
        time_start: '13:30',
        meeting_section: '(05)',
        section: 1074,
        section_type: 'L',
        enrolment: 0,
        day: 'R',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1074,
        size: 30,
        time_start: '11:00',
        meeting_section: '(05)',
        section: 1074,
        section_type: 'L',
        enrolment: 0,
        day: 'F',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1074,
        size: 30,
        time_start: '11:00',
        meeting_section: '(05)',
        section: 1074,
        section_type: 'L',
        enrolment: 0,
        day: 'W',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1074,
        size: 30,
        time_start: '11:00',
        meeting_section: '(05)',
        section: 1074,
        section_type: 'L',
        enrolment: 0,
        day: 'M',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
    ],
    '(03)': [
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '17:20',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1072,
        size: 30,
        time_start: '16:30',
        meeting_section: '(03)',
        section: 1072,
        section_type: 'L',
        enrolment: 0,
        day: 'R',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '10:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1072,
        size: 30,
        time_start: '10:00',
        meeting_section: '(03)',
        section: 1072,
        section_type: 'L',
        enrolment: 0,
        day: 'F',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '10:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1072,
        size: 30,
        time_start: '10:00',
        meeting_section: '(03)',
        section: 1072,
        section_type: 'L',
        enrolment: 0,
        day: 'W',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '10:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1072,
        size: 30,
        time_start: '10:00',
        meeting_section: '(03)',
        section: 1072,
        section_type: 'L',
        enrolment: 0,
        day: 'M',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
    ],
    '(08)': [
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '15:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1077,
        size: 30,
        time_start: '15:00',
        meeting_section: '(08)',
        section: 1077,
        section_type: 'L',
        enrolment: 0,
        day: 'T',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1077,
        size: 30,
        time_start: '11:00',
        meeting_section: '(08)',
        section: 1077,
        section_type: 'L',
        enrolment: 0,
        day: 'F',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1077,
        size: 30,
        time_start: '11:00',
        meeting_section: '(08)',
        section: 1077,
        section_type: 'L',
        enrolment: 0,
        day: 'W',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1077,
        size: 30,
        time_start: '11:00',
        meeting_section: '(08)',
        section: 1077,
        section_type: 'L',
        enrolment: 0,
        day: 'M',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
    ],
    '(09)': [
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '14:20',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1078,
        size: 30,
        time_start: '13:30',
        meeting_section: '(09)',
        section: 1078,
        section_type: 'L',
        enrolment: 0,
        day: 'T',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1078,
        size: 30,
        time_start: '11:00',
        meeting_section: '(09)',
        section: 1078,
        section_type: 'L',
        enrolment: 0,
        day: 'F',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1078,
        size: 30,
        time_start: '11:00',
        meeting_section: '(09)',
        section: 1078,
        section_type: 'L',
        enrolment: 0,
        day: 'W',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '11:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1078,
        size: 30,
        time_start: '11:00',
        meeting_section: '(09)',
        section: 1078,
        section_type: 'L',
        enrolment: 0,
        day: 'M',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
    ],
    '(02)': [
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '15:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1071,
        size: 30,
        time_start: '15:00',
        meeting_section: '(02)',
        section: 1071,
        section_type: 'L',
        enrolment: 0,
        day: 'T',
        textbooks: [

        ],
        location: '',
        was_full: false,
        colourId: 0,
        code: 'AS.110.106',
        name: 'Calculus I (Biology and Social Sciences)',
        custom: false,
        num_conflicts: 1,
        shift_index: 0,
        depth_level: 0,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '10:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1071,
        size: 30,
        time_start: '10:00',
        meeting_section: '(02)',
        section: 1071,
        section_type: 'L',
        enrolment: 0,
        day: 'F',
        textbooks: [

        ],
        location: '',
        was_full: false,
        colourId: 0,
        code: 'AS.110.106',
        name: 'Calculus I (Biology and Social Sciences)',
        custom: false,
        num_conflicts: 2,
        shift_index: 1,
        depth_level: 0,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '10:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1071,
        size: 30,
        time_start: '10:00',
        meeting_section: '(02)',
        section: 1071,
        section_type: 'L',
        enrolment: 0,
        day: 'W',
        textbooks: [

        ],
        location: '',
        was_full: false,
        colourId: 0,
        code: 'AS.110.106',
        name: 'Calculus I (Biology and Social Sciences)',
        custom: false,
        num_conflicts: 2,
        shift_index: 1,
        depth_level: 0,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '10:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1071,
        size: 30,
        time_start: '10:00',
        meeting_section: '(02)',
        section: 1071,
        section_type: 'L',
        enrolment: 0,
        day: 'M',
        textbooks: [

        ],
        location: '',
        was_full: false,
        colourId: 0,
        code: 'AS.110.106',
        name: 'Calculus I (Biology and Social Sciences)',
        custom: false,
        num_conflicts: 2,
        shift_index: 1,
        depth_level: 0,
      },
    ],
    '(01)': [
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '17:20',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1070,
        size: 30,
        time_start: '16:30',
        meeting_section: '(01)',
        section: 1070,
        section_type: 'L',
        enrolment: 0,
        day: 'T',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '10:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1070,
        size: 30,
        time_start: '10:00',
        meeting_section: '(01)',
        section: 1070,
        section_type: 'L',
        enrolment: 0,
        day: 'F',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '10:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1070,
        size: 30,
        time_start: '10:00',
        meeting_section: '(01)',
        section: 1070,
        section_type: 'L',
        enrolment: 0,
        day: 'W',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
      {
        waitlist: -1,
        instructors: 'R. Brown',
        time_end: '10:50',
        waitlist_size: -1,
        course: 411,
        semester: 4,
        _semester: '',
        id: 1070,
        size: 30,
        time_start: '10:00',
        meeting_section: '(01)',
        section: 1070,
        section_type: 'L',
        enrolment: 0,
        day: 'M',
        textbooks: [

        ],
        location: '',
        was_full: false,
      },
    ],
  },
  tutorialSections: {

  },
  practicalSections: {

  },
  hasHoveredResult: false,
  prerequisites: '',
  description: 'Differential and integral calculus. Includes analytic geometry, functions, limits, integrals and\r\nderivatives, introduction to differential equations, functions of several variables, linear systems,\r\napplications for systems of linear differential equations, probability distributions. Many\r\napplications to the biological and social sciences will be discussed.',
  popularityPercent: 1.1111111111111,
  inRoster: true,
  isLoggedIn: true,
  hasSocial: true,
  userInfo: {
    GoogleLoggedIn: true,
    major: 'Accounting',
    emails_enabled: true,
    GoogleSignedUp: true,
    school: 'jhu',
    fbook_uid: '10206009352974277',
    gender: 'male',
    timetables: [
      {
        school: 'jhu',
        last_updated: '2017-05-15 01:28:26.034529+00:00',
        name: 'asdf',
        has_conflict: false,
        avg_rating: 3.7733333333333,
        courses: [
          {
            code: 'AS.110.106',
            num_credits: 4,
            related_courses: [

            ],
            unstopped_description: '',
            slots: [
              {
                time_start: '13:30',
                waitlist: -1,
                meeting_section: '(05)',
                section: 1074,
                instructors: 'R. Brown',
                section_type: 'L',
                enrolment: 0,
                id: 5619,
                waitlist_size: -1,
                course: 411,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [

                ],
                time_end: '14:20',
                was_full: false,
                day: 'R',
                size: 30,
                colourId: 0,
                code: 'AS.110.106',
                name: 'Calculus I (Biology and Social Sciences)',
                custom: false,
                num_conflicts: 1,
                shift_index: 0,
                depth_level: 0,
              },
              {
                time_start: '11:00',
                waitlist: -1,
                meeting_section: '(05)',
                section: 1074,
                instructors: 'R. Brown',
                section_type: 'L',
                enrolment: 0,
                id: 5618,
                waitlist_size: -1,
                course: 411,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [

                ],
                time_end: '11:50',
                was_full: false,
                day: 'F',
                size: 30,
                colourId: 0,
                code: 'AS.110.106',
                name: 'Calculus I (Biology and Social Sciences)',
                custom: false,
                num_conflicts: 1,
                shift_index: 0,
                depth_level: 0,
              },
              {
                time_start: '11:00',
                waitlist: -1,
                meeting_section: '(05)',
                section: 1074,
                instructors: 'R. Brown',
                section_type: 'L',
                enrolment: 0,
                id: 5617,
                waitlist_size: -1,
                course: 411,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [

                ],
                time_end: '11:50',
                was_full: false,
                day: 'W',
                size: 30,
                colourId: 0,
                code: 'AS.110.106',
                name: 'Calculus I (Biology and Social Sciences)',
                custom: false,
                num_conflicts: 1,
                shift_index: 0,
                depth_level: 0,
              },
              {
                time_start: '11:00',
                waitlist: -1,
                meeting_section: '(05)',
                section: 1074,
                instructors: 'R. Brown',
                section_type: 'L',
                enrolment: 0,
                id: 5616,
                waitlist_size: -1,
                course: 411,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [

                ],
                time_end: '11:50',
                was_full: false,
                day: 'M',
                size: 30,
                colourId: 0,
                code: 'AS.110.106',
                name: 'Calculus I (Biology and Social Sciences)',
                custom: false,
                num_conflicts: 1,
                shift_index: 0,
                depth_level: 0,
              },
            ],
            enrolled_sections: [
              '(05)',
            ],
            campus: '',
            id: 411,
            department: 'AS Mathematics',
            geneds: null,
            description: 'Differential and integral calculus. Includes analytic geometry, functions, limits, integrals and\r\nderivatives, introduction to differential equations, functions of several variables, linear systems,\r\napplications for systems of linear differential equations, probability distributions. Many\r\napplications to the biological and social sciences will be discussed.',
            corequisites: '',
            is_waitlist_only: false,
            areas: 'Q',
            info: '',
            school: 'jhu',
            name: 'Calculus I (Biology and Social Sciences)',
            level: '100',
            prerequisites: '',
            notes: '',
            textbooks: {
              '(05)': [

              ],
            },
            cores: null,
            exclusions: '',
          },
          {
            code: 'EN.553.171',
            num_credits: 4,
            related_courses: [

            ],
            unstopped_description: '',
            slots: [
              {
                time_start: '09:00',
                waitlist: -1,
                meeting_section: '(01)',
                section: 4663,
                instructors: 'B. Castello',
                section_type: 'L',
                enrolment: 0,
                id: 8777,
                waitlist_size: -1,
                course: 1710,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [
                  9780840049421,
                ],
                time_end: '09:50',
                was_full: false,
                day: 'R',
                size: 25,
                colourId: 1,
                code: 'EN.553.171',
                name: 'Discrete Mathematics',
                custom: false,
                num_conflicts: 1,
                shift_index: 0,
                depth_level: 0,
              },
              {
                time_start: '10:00',
                waitlist: -1,
                meeting_section: '(01)',
                section: 4663,
                instructors: 'B. Castello',
                section_type: 'L',
                enrolment: 0,
                id: 8776,
                waitlist_size: -1,
                course: 1710,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [
                  9780840049421,
                ],
                time_end: '10:50',
                was_full: false,
                day: 'F',
                size: 25,
                colourId: 1,
                code: 'EN.553.171',
                name: 'Discrete Mathematics',
                custom: false,
                num_conflicts: 1,
                shift_index: 0,
                depth_level: 0,
              },
              {
                time_start: '10:00',
                waitlist: -1,
                meeting_section: '(01)',
                section: 4663,
                instructors: 'B. Castello',
                section_type: 'L',
                enrolment: 0,
                id: 8775,
                waitlist_size: -1,
                course: 1710,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [
                  9780840049421,
                ],
                time_end: '10:50',
                was_full: false,
                day: 'W',
                size: 25,
                colourId: 1,
                code: 'EN.553.171',
                name: 'Discrete Mathematics',
                custom: false,
                num_conflicts: 1,
                shift_index: 0,
                depth_level: 0,
              },
              {
                time_start: '10:00',
                waitlist: -1,
                meeting_section: '(01)',
                section: 4663,
                instructors: 'B. Castello',
                section_type: 'L',
                enrolment: 0,
                id: 8774,
                waitlist_size: -1,
                course: 1710,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [
                  9780840049421,
                ],
                time_end: '10:50',
                was_full: false,
                day: 'M',
                size: 25,
                colourId: 1,
                code: 'EN.553.171',
                name: 'Discrete Mathematics',
                custom: false,
                num_conflicts: 1,
                shift_index: 0,
                depth_level: 0,
              },
            ],
            enrolled_sections: [
              '(01)',
            ],
            campus: '',
            id: 1710,
            department: 'EN Applied Mathematics & Statistics',
            geneds: null,
            description: 'Introduction to the mathematics of finite systems. Logic; Boolean algebra; induction and recursion; sets, functions, relations, equivalence, and partially ordered sets; elementary combinatorics; modular arithmetic and the Euclidean algorithm; group theory; permutations and symmetry groups; graph theory. Selected applications. The concept of a proof and development of the ability to recognize and construct proofs are part of the course. Recommended Course Background: Four years of high school mathematics.',
            corequisites: '',
            is_waitlist_only: false,
            areas: 'Q',
            info: '',
            school: 'jhu',
            name: 'Discrete Mathematics',
            level: '100',
            prerequisites: '',
            notes: '',
            textbooks: {
              '(01)': [
                {
                  image_url: 'https:\/\/images-na.ssl-images-amazon.com\/images\/I\/51V7MmrodSL._SL160_.jpg',
                  detail_url: 'https:\/\/www.amazon.com\/Mathematics-Discrete-Introduction-Edward-Scheinerman\/dp\/0840049420?SubscriptionId=***REMOVED***&tag=semesterly-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=0840049420',
                  isbn: 9780840049421,
                  title: 'Mathematics: A Discrete Introduction',
                  author: 'Edward A. Scheinerman',
                },
              ],
            },
            cores: null,
            exclusions: '',
          },
        ],
        semester: 4,
        _semester: '',
        student: 1,
        sections: [
          1074,
          4663,
        ],
        id: 12,
      },
      {
        school: 'jhu',
        last_updated: '2017-04-07 15:30:00.708846+00:00',
        name: 'calc',
        has_conflict: false,
        avg_rating: 3.9166666666667,
        courses: [
          {
            code: 'AS.110.105',
            num_credits: 4,
            related_courses: [

            ],
            unstopped_description: '',
            slots: [
              {
                time_start: '13:30',
                waitlist: -1,
                meeting_section: '(01)',
                section: 1069,
                instructors: 'Staff',
                section_type: 'L',
                enrolment: 0,
                id: 5599,
                waitlist_size: -1,
                course: 410,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [

                ],
                time_end: '14:20',
                was_full: false,
                day: 'T',
                size: 30,
              },
              {
                time_start: '09:00',
                waitlist: -1,
                meeting_section: '(01)',
                section: 1069,
                instructors: 'Staff',
                section_type: 'L',
                enrolment: 0,
                id: 5598,
                waitlist_size: -1,
                course: 410,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [

                ],
                time_end: '09:50',
                was_full: false,
                day: 'F',
                size: 30,
              },
              {
                time_start: '09:00',
                waitlist: -1,
                meeting_section: '(01)',
                section: 1069,
                instructors: 'Staff',
                section_type: 'L',
                enrolment: 0,
                id: 5597,
                waitlist_size: -1,
                course: 410,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [

                ],
                time_end: '09:50',
                was_full: false,
                day: 'W',
                size: 30,
              },
              {
                time_start: '09:00',
                waitlist: -1,
                meeting_section: '(01)',
                section: 1069,
                instructors: 'Staff',
                section_type: 'L',
                enrolment: 0,
                id: 5596,
                waitlist_size: -1,
                course: 410,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [

                ],
                time_end: '09:50',
                was_full: false,
                day: 'M',
                size: 30,
              },
            ],
            enrolled_sections: [
              '(01)',
            ],
            campus: '',
            id: 410,
            department: 'AS Mathematics',
            geneds: null,
            description: 'This course starts from scratch and provides students with all the background necessary for the study of calculus. It includes a review of algebra, trigonometry, exponential and logarithmic functions, coordinates and graphs. Each of these tools will be introduced in its cultural and historical context. The concept of the rate of change of a function will be introduced. Not open to students who have studied calculus in high school.',
            corequisites: '',
            is_waitlist_only: false,
            areas: 'Q',
            info: '',
            school: 'jhu',
            name: 'Introduction to Calculus',
            level: '100',
            prerequisites: '',
            notes: '',
            textbooks: {
              '(01)': [

              ],
            },
            cores: null,
            exclusions: '',
          },
          {
            code: 'AS.110.106',
            num_credits: 4,
            related_courses: [

            ],
            unstopped_description: '',
            slots: [
              {
                time_start: '16:30',
                waitlist: -1,
                meeting_section: '(06)',
                section: 1075,
                instructors: 'R. Brown',
                section_type: 'L',
                enrolment: 0,
                id: 5623,
                waitlist_size: -1,
                course: 411,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [

                ],
                time_end: '17:20',
                was_full: false,
                day: 'R',
                size: 30,
              },
              {
                time_start: '11:00',
                waitlist: -1,
                meeting_section: '(06)',
                section: 1075,
                instructors: 'R. Brown',
                section_type: 'L',
                enrolment: 0,
                id: 5622,
                waitlist_size: -1,
                course: 411,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [

                ],
                time_end: '11:50',
                was_full: false,
                day: 'F',
                size: 30,
              },
              {
                time_start: '11:00',
                waitlist: -1,
                meeting_section: '(06)',
                section: 1075,
                instructors: 'R. Brown',
                section_type: 'L',
                enrolment: 0,
                id: 5621,
                waitlist_size: -1,
                course: 411,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [

                ],
                time_end: '11:50',
                was_full: false,
                day: 'W',
                size: 30,
              },
              {
                time_start: '11:00',
                waitlist: -1,
                meeting_section: '(06)',
                section: 1075,
                instructors: 'R. Brown',
                section_type: 'L',
                enrolment: 0,
                id: 5620,
                waitlist_size: -1,
                course: 411,
                semester: 4,
                _semester: '',
                location: '',
                is_section_filled: false,
                textbooks: [

                ],
                time_end: '11:50',
                was_full: false,
                day: 'M',
                size: 30,
              },
            ],
            enrolled_sections: [
              '(06)',
            ],
            campus: '',
            id: 411,
            department: 'AS Mathematics',
            geneds: null,
            description: 'Differential and integral calculus. Includes analytic geometry, functions, limits, integrals and\r\nderivatives, introduction to differential equations, functions of several variables, linear systems,\r\napplications for systems of linear differential equations, probability distributions. Many\r\napplications to the biological and social sciences will be discussed.',
            corequisites: '',
            is_waitlist_only: false,
            areas: 'Q',
            info: '',
            school: 'jhu',
            name: 'Calculus I (Biology and Social Sciences)',
            level: '100',
            prerequisites: '',
            notes: '',
            textbooks: {
              '(06)': [

              ],
            },
            cores: null,
            exclusions: '',
          },
        ],
        semester: 4,
        _semester: '',
        student: 1,
        sections: [
          1069,
          1075,
        ],
        id: 11,
      },
    ],
    FacebookSignedUp: true,
    social_offerings: true,
    class_year: 2017,
    social_all: true,
    userFirstName: 'Noah',
    integrations: [

    ],
    isLoggedIn: true,
    userLastName: 'Presler',
    LoginHash: 'KR',
    social_courses: true,
    LoginToken: '1dAPXe:s94jv8JVHrHW8J7hg9afwnoMKfU',
    img_url: 'https:\/\/scontent.xx.fbcdn.net\/v\/t1.0-1\/p50x50\/18193968_10208799143997309_4182518417368859549_n.jpg?oh=c2805b229bc9b4a785c7c78d8520eaf3&oe=59AECF0A',
  },
};

export default courseModalBodyFixture;

/* eslint-enable no-useless-escape */
