# Generated by Django 3.2.7 on 2022-03-05 01:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsupdate',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
